### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by pacuna** [rocketeers/rocketeer#104]
I'm getting this message when I run deploy

```
Cloning repository in "/var/www/fotea/releases/20140119051639"
Unable to clone the repository
Cloning into '/var/www/fotea/releases/20140119051639'...
Host key verification failed.
fatal: The remote end hung up unexpectedly
Rolling back to release 20140119042209
Execution time: 34.5702s
```

I've tried all the typical solutions like ssh-key -r host, remove known_host and connect by ssh again, but nothing works.

Any suggestions?

pd: deploy:check works fine so it's not a ssh keys problem.

**Comment by deresh** [comment]
This is also a problem with deploying to new server, as when you first time connect to remote git server you need to accept host key verification.

@sharedmit: workaround is to login to server and manualy ssh to your git url, and accept host verification. Then on next deployments it won't be an issue anymore.
