### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by trsteel88** [rocketeers/rocketeer#147]
I was trying out Rocketeer today to see if I could get it setup for a Symfony app. I am getting the following error:

```
Checking presence of git
Checking PHP version
Checking presence of Composer
Checking presence of mcrypt extension
The version of PHP on the server does not match Laravel's requirements
Deployment was canceled by task "Check"
```

I am assuming that the Rocketeer is built ontop of Lavarel? If so, what version does it require?

**Comment by slk500** [comment]
Hey I have the same problem "PHP is not at the required version" . In Json - "php": ">=5.5.9", on server - Current PHP version: 7.0.9

**Comment by Anahkiasen** [comment]
Can you run `$task->php()->run('version')`, what does that yield?

**Comment by slk500** [comment]
where I can run this? I have tried to put this in example.php on server file like phpinfo().

**Comment by Anahkiasen** [comment]
There is a `tinker` REPL command on Rocketeer, you could go in there and IIRC you should have an `$app` variable representing Rocketeer's container on which you can call `$app->bash->php()->run('version')`

**Comment by slk500** [comment]
rocketeer tinker [enter]
[1] rocketeer> $app->bash->php()->run('version'); [enter]
PHP Notice:  Undefined variable: app in phar:///usr/local/bin/rocketeer/vendor/d11wtq/boris/lib/Boris/EvalWorker.php(152) : eval()'d code on line 1
...

**Comment by Anahkiasen** [comment]
Ah shit sorry, `$app` is Rocketeer 3, in Rocketeer 2 it's `$rocketeer`, sorry :D

**Comment by Anahkiasen** [comment]
If you wanna do this faster ping me on the Gitter chat we'll debug this together
