### ISSUE TITLE
How to run a custom task right before symlinking the new release?

### ISSUE THREAD

**Issue by thomasmeeus** [rocketeers/rocketeer#184]
Hi,

I wrote some custom tasks for npm, grunt and bower. I want them to run in the latest release folder right before symlinking. How can I do that?

For now I have: 
- `.rocketeer/tasks/Bower.php`

``` php
<?php
class Bower extends Rocketeer\Traits\Task
{
  /**
   * Description of the Task
   *
   * @var string
   */
  protected $description = 'Runs "Bower install"';

  /**
   * Executes the Task
   *
   * @return void
   */
  public function execute()
  {
    $this->command->info('Running "Bower install"');
    $this->runForCurrentRelease('bower install');
  }
}
?>
```

In `.rocketeer/tasks/hooks.php` I have the following:

``` php
'after' => array(
        'setup'   => array(),
        'deploy'  => array('Bower'),
        'cleanup' => array(),
    )
```

This works, but the tasks are executed after symlinking which will cause downtime of my app. How can I execute these tasks just before symlinking?

I found something like this, but don't know were to put it (my php knowledge is really bad :smile:)

``` php
Rocketeer::listenTo('deploy.before-symlink', function ($task) {
  echo $task->releasesManager->getCurrentRelease();
});
```

**Comment by FlorianCP** [comment]
I guess the docs should mention the needed use directive here: http://rocketeer.autopergamene.eu/#/docs/docs/II-Concepts/Events
