### ISSUE TITLE
Unable to connect to remote server with SSH-Key

### ISSUE THREAD

**Issue by divdax** [rocketeers/rocketeer#188]
Hey everyone,

i've setup rocketeer the first time with Laravel 4.1 using the following login credentials:

```
    'connections' => array(

        'production' => array(
            'host'      => 'xx.xx.xx.xx',
            'username'  => 'deploy',
            'password'  => '',
            'key'       => '/Users/divdax/Sites/app/ssh-key',
            'keyphrase' => '',
            'root'      => '/var/www',
        ),

    ),
```

After hitting "rocketeer check" i get the following error:

```
[RuntimeException]
  Unable to connect to remote server.
```

If i connect via ssh to my server with the same userdata and key the login works fine but not with rocketeer. What i'm doing wrong? The keypath is also correct...

**Comment by marcovtwout** [comment]
@cerw Thanks!

**Comment by cerw** [comment]
But agent still not working for me :(
