### ISSUE TITLE
Prompt for server ssh keyphrase?

### ISSUE THREAD

**Issue by ZenVentures** [rocketeers/rocketeer#190]
Is it possible to have rocketeer prompt for the ssh keyphrase to connect to the remote?
It seems if right now you give it a key with a passphrase and leave passphrase blank, it assumes you are using a key with NO passphrase and the connection fails.

Maybe there is a way to do this and I am misunderstanding something?

Thanks

Edits: retitled and made issue about one thing.

**Comment by marcovtwout** [comment]
Could you reopen this issue?

**Comment by marcovtwout** [comment]
Could you reopen this issue?

Also, I don't think this is documented anywhere:

```
Basically now, instead of having credentials internally marked as required or not, there are four ways to define credentials:

'foobar' - value is required and set, will never be prompted for it
'' - value is required, will be prompted for it once, then saved to disk
true - value is required, but will be prompted for it every time, never saved to disk
false|null - value is not required/needed, will never be prompted for it
```

**Comment by Anahkiasen** [comment]
Issue is already reopened, it's documented in the configuration https://github.com/rocketeers/rocketeer/blob/develop/src/config/config.php#L35

**Comment by Anahkiasen** [comment]
Should be working now

**Comment by marcovtwout** [comment]
Confirmed, thanks!

**Comment by simplesi** [comment]
Thanks for making this change.
When will this be released? I see this isn't in 2.2.0.

**Comment by Giakie** [comment]
first of all, thanks for your amazing work!
I see that this feature is in the Development branch but not on Master; when will this be released? It would be a great to have this, useful for sharing the basic configurations in a project repository with the team, but allowing everyone to deploy only on a staging environment, for example, and not on production, by leaving empty the latter password

thanks!

**Comment by choonge** [comment]
+1 for merging to master

**Comment by lwrbakro** [comment]
+1 for merging
