### ISSUE TITLE
SVN username and password not passed to `svn co`

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#192]
I have setup Rocketeer to deploy using my svn repository. When I execute `rocketeer deploy`, I run into the following error:

```
Cloning repository in "/data/www/xxx/releases/20140318163638"
Unable to clone the repository
svn: E170001: Unable to connect to a repository at URL 'svn://localhost/test/trunk'
```

Final lines from logs/production--xxx.log:

```
[2014-03-18 20:36:39] rocketeer.INFO: ["svn co --non-interactive svn:\/\/localhost\/xxx\/trunk \/data\/www\/xxx\/releases\/20140318163638"] [] []
[2014-03-18 20:36:39] rocketeer.INFO: svn: E170001: Unable to connect to a repository at URL 'svn://localhost/test/trunk'
svn: E170001: Can't get username or password [] []
```

My scm.php looks like this:

```
<?php return array(
    'scm' => 'svn',
    'repository' => 'svn://localhost/test',
    'username'   => 'xxx',
    'password'   => 'xxx',
        (...)
);
```

When I look at the source code, the username and password should be passed to the checkout command, but as you can see in the log file, they are being omitted. https://github.com/Anahkiasen/rocketeer/blob/3591b74208e632ce5ffe090ffcd19330785feb77/src/Rocketeer/Scm/Svn.php#L80

**Comment by lce-fr** [comment]
I have the same issue but for git cloning with v 2.1.2 on debian 7

I cannot manage to get the repository cloned with a password (prompted or not ): 

my scm.php:

`̀``php

    // The SCM used (supported: "git", "svn")
    'scm'        => 'git',
    'repository' => 'user@xx.xx.xx.xx:/path/to/repo'
    'username'   => 'user',
    'password'   => ''',
    'branch'     => 'dev',
    'shallow'    => true,
    'submodules' => true,
```

rocketeer tries do to : git clone "user@xx.xx.xx.xx:/path/to/repo "/path/to/prod/releases/20150811190024" --branch="dev" --depth="1"

 git clone "user@xx.xx.xx.xx:/path/to/repo" works on my terminal, it prompts me the password.

Kind regards


Kind regards
