### ISSUE TITLE
Protecting Sensitive Configuration

### ISSUE THREAD

**Issue by barryvdh** [rocketeers/rocketeer#224]
Following the tips from the Laravel docs on sensitive information (http://laravel.com/docs/configuration#protecting-sensitive-configuration), what would you suggest what would be the best way to handle this using Rocketeer? Something similar to #150, by copying it in task?
Would this be useful to include in the core (as it is the suggested approach by Laravel)?

I want to prevent having to put my database passwd/keys etc in the git repo.

**Comment by imolorhe** [comment]
@Anahkiasen Do we still need to create a task to upload the .env file? Or does the deploy automatically handle the .env file?
