### ISSUE TITLE
deploy:check and hhvm

### ISSUE THREAD

**Issue by pschmidt88** [rocketeers/rocketeer#237]
if you have sym linked `php` to `hhvm` on the remote server `deploy:check` does not work.

the script just stucks when checking for the mcrypt extension. it's because "php -m" (you can only check for the hhvm version with php -v / hhvm -v) does not return anything. (this won't work for other extension checks as well)

as far as i know the mcrypt extension is built-in in hhvm. if you would check for hhvm (before executing php -m) that would be enough.

**Comment by skenmy** [comment]
This seems to have regressed - both stable and dev-master unfortunately hang at `Checking presence of required extensions`.

HHVM version 3.5.0
````bash
hphpd> print defined('HHVM_VERSION') ? HHVM_VERSION : PHP_VERSION;
print defined('HHVM_VERSION') ? HHVM_VERSION : PHP_VERSION;
"3.5.0"
hphpd> print defined('HHVM_VERSION');
print defined('HHVM_VERSION');
true
hphpd> print HHVM_VERSION;
print HHVM_VERSION;
"3.5.0"
hphpd> print PHP_VERSION;
print PHP_VERSION;
"5.6.99-hhvm"
````
