### ISSUE TITLE
Deployment: git clone "https://username:password@github.com". Could not resolve host: username

### ISSUE THREAD

**Issue by nestorconde** [rocketeers/rocketeer#251]
I'm using the laravel homestead virtual machine (http://laravel.com/docs/homestead), that means Ubuntu 14.04 and git version 1.9.1. "rocketeer deploy" does not work because there is a problem with the cloning of the repo. After some investigation it seems that the following command is issued in the target machine:

```
git clone --depth 1 -b master "https://username:password@github.com/vendor/repo.git" /home/www/rocketeer/releases/20140712223030
```

I get the following error:

```
fatal: unable to access 'https://username:password@github.com/vendor/repo.git/': Could not resolve host: username
```

Seems like the username and password are not interpreted as such but seen as part of the domain. This could be an issue not related to rocketeer but I'm not sure where it should be reported otherwise, and anyway perhaps can be useful for rocketeer too :)

**Comment by Bendo2** [comment]
what was the answer? What did you do the fix it exactly???
command line example would help.
Thanks

**Comment by Anahkiasen** [comment]
I think he means there was per example a space in his username or password that needed to be `%20`, otherwise the URL was parsed wrong
