### ISSUE TITLE
Hide password input

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#296]
When Rocketeer prompt to enter a password, it is displayed in plain text while typing (on Windows). Is there a way to hide this, typical to most other terminal login prompts?

**Comment by marcovtwout** [comment]
Could you reopen this issue?

**Comment by Anahkiasen** [comment]
This has been changed, keyphrase should be hidden on develop, isn't it the case?

**Comment by marcovtwout** [comment]
I cannot confirm this right now because of #190
