### ISSUE TITLE
relative symlinks

### ISSUE THREAD

**Issue by Krienas** [rocketeers/rocketeer#363]
Hello,

is there a way to configure Rocketeer to create relative symlinks instead of absolute ones? 'current' could simply point to 'releases/[release_name]'. Now deployments for me work only if I let webserver to access all directories all way to the root of disk or fix that symlink to relative

**Comment by tgerulaitis** [comment]
Hi,

Has this issue ever been resolved? The web server I'm deploying to runs in a chroot, so relative symlinks are a must to be able to use rocketeer.

I've noticed that the pull request (#368) was closed but never merged into develop. Any plans to support this in the future?

**Comment by Anahkiasen** [comment]
It is supported, check the relative symlink option in remote.php

**Comment by tgerulaitis** [comment]
Ah! I was checking the wrong branch! Good work :)
