### ISSUE TITLE
Deploying to just one server on a connection?

### ISSUE THREAD

**Issue by ShonM** [rocketeers/rocketeer#376]
I have a use case for Rocketeer that involves deploying an arbitrary branch to an arbitrary node within a connection. This is the QA stage, where each node has its own domain, but many of them can be on the same branch.

For now, I'm using separate connections for each of the QA nodes, but, is there a better way to do this that I could, for example deploy `develop` to 2/3 of those nodes, that I can't yet see?

I think a `--servers` flag would be plenty to support this, and a full deploy might look like `rocketeer deploy --on=qa --servers=qa1,qa2` or `--servers=qa1 --servers=qa2` (it's all automated anyways, I don't plan to type out any of this). I only suggest the name `servers` because of the connection key name for more than one host. Really, I'd be happy with anything, so, if this doesn't yet exist I'm happy to code it up and submit a PR. Just need to work out some other connection specifics and figure out how best to separate all the work... I'm also using SSH agent forwarding from another fork, and reverted the `mv -T` code because I'm on FreeBSD. It's a frankenstein right now :)

**Comment by ShonM** [comment]
This doesn't seem to be doing what I expect. If deploying, it deploys to all nodes. If running a single task, it properly only runs on a single server.

**Comment by Anahkiasen** [comment]
@ShonM What do you mean by all nodes?

**Comment by ShonM** [comment]
It's been so long... At this point, I only use Rocketeer as a task runner and did away with all its connection / SSH / servers. It only runs "local", being called by a synchronized/concurrent set of daemons running on each server in an environment.

**Comment by Anahkiasen** [comment]
Ok well, will close this and reopen if anybody wants to take the feature further, thanks!
