### ISSUE TITLE
Server Roles

### ISSUE THREAD

**Issue by ShonM** [rocketeers/rocketeer#380]
Please bare with me if this sounds stupid, but... Is there any concept of roles or groups? I caught a couple mentions of this, but it's very scattered (here's one https://github.com/rocketeers/rocketeer/issues/37#issuecomment-22988150), so I wanted to focus the discussion a bit. Let me explain how I would like to deploy, maybe there's something that fits...
1. Grab new code, deps, et al _on every server_
2. Build PHP-land caches (templating, containers, etc) _on every server_
3. Build assets _only on the static asset server_
4. Reload the web server _only on the web server_

More than that, I'd love if I could do all the code updates on all servers, then only build assets on just the asset server, and the same thing for the web server. So it's something like "grouping tasks on servers within a connection" or something like that.

Is this something I could hack together easily? Is there a clear official path to get it into the codebase? If so, I'd be happy to start figuring that out and submit a PR back once I've got it all figured out.

**Comment by bkuhl** [comment]
Thanks for the followup @ShonM, I'm using your approach.
