### ISSUE TITLE
Composer install not firing on v2.0.4, but works in v2.0.3 non-laravel app

### ISSUE THREAD

**Issue by mikemunger** [rocketeers/rocketeer#395]
When using the exact same .rocketeer/*.php configuration files, a "rocketeer deploy" fails in v2.0.4 because composer install is not firing (according to "rocketeer deploy -v").  However if all I do is swap out the rocketeer.phar in use from v 2.0.4 to v2.0.3, composer install does fire and the "rocketeer deploy" completes successfully with everything else being equal.

This is for a non-laravel app I am deploying.

Edit: I should probably also mention I am using a custom path to composer in .rocketeer/paths.php

**Comment by Anahkiasen** [comment]
Also can you test with `2.1-dev` see if it hasn't been fixed meanwhile

**Comment by mikemunger** [comment]
I am happy to test these things, time permitting.

I need to setup a 3rd mock-production instance (so as not to break production) which I won't be able to do for a couple weeks due to my current work load.

This is also the reason I have not followed up with output pasting, so I apologize for that.

Thank you for responding to the issue, I hope to get to testing it in February sometime.

**Comment by mikemunger** [comment]
I finally moved to 2.0.5, and I no longer have this issue. Can't really do enough testing to verify why.  It might have had to do with an error causing the deployment to abort in the git checkout process with 'submodules' => true when I don't need this and might have had a blank directory in my library autoload folder it failed on. It seems maybe 2.0.4 symlinked the release in this state "breaking" my production site, but in 2.0.5 it correctly aborts the deployment and leaves the previous working release intact.
