### ISSUE TITLE
segmentation fault in deploy procedure

### ISSUE THREAD

**Issue by domnulnopcea** [rocketeers/rocketeer#397]
Hi,

I have just set up rocketeer. Configured a git repo, the credentials for the server BUT in strategies.php instead of

	'dependencies' => 'Polyglot',

	// Execution hooks
	//////////////////////////////////////////////////////////////////////

	'composer'     => array(
		'install' => function (Composer $composer, $task) {
			return $composer->install([], ['--no-interaction' => null, '--no-dev' => null, '--prefer-dist' => null]);
		},
		'update'  => function (Composer $composer) {
			return $composer->update();
		},
	),

I have set

	'dependencies' => '',

	// Execution hooks
	//////////////////////////////////////////////////////////////////////

	'composer'     => array(
		'install' => function (Composer $composer, $task) {
			return $composer->install([], ['--no-interaction' => null, '--no-dev' => null, '--prefer-dist' => null]);
		},
		'update'  => function (Composer $composer) {
			return $composer->update();
		},
	),

notice the "Polyglot" string removed.

If I do a deploy now it gives a segmentation fault when in tries to install/update composer packages.

thanks

**Comment by Anahkiasen** [comment]
Should be fixed on develop
