### ISSUE TITLE
Deploy notifier user command line flag

### ISSUE THREAD

**Issue by ShonM** [rocketeers/rocketeer#399]
I'd love for this to exist; just a flag like `--name="Mr Deploy"`, so that automated deploy mechanisms can set their own names up. If this would be valuable, I'm happy to codify and submit a PR, otherwise I will hack myself up my own version in my specific deploy code, because my current Rocketeer is a frankenstein :)

**Comment by Anahkiasen** [comment]
Can't the name just be set in the plugin's configuration, it shouldn't ask it then, no?

**Comment by ShonM** [comment]
I have more learning to do still it seems. How would that be configured? How could it sit outside version control? I want to say "it's just PHP", but maybe there's a trick I don't know about Rocketeer that might help me. If there's no tricks, I think I got something that will work.

**Comment by ShonM** [comment]
I overrode some code to pull this out of the environment, and that works a treat for me!
