### ISSUE TITLE
Conflict with Composer requirements

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#401]
I have these two conflicting packages in my composer.json:

    "apigen/apigen": "~4.0",
    "anahkiasen/rocketeer": "~2.0"

Running `composer update` results in a conflict for requirement symfony/console:

    - apigen/apigen v4.0.0 requires symfony/console ~2.6 -> satisfiable by symfony/console[v2.6.3, v2.6.0, v2.6.1, v2.6.2].
    - Can only install one of: symfony/console[v2.6.0, v2.5.0].
    - Can only install one of: symfony/console[v2.6.1, v2.5.0].
    - illuminate/console v4.2.1 requires symfony/console 2.5.* -> satisfiable by symfony/console[v2.5.0, v2.5.1, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].

How can I solve this problem? `illuminate/console dev-master` already requires 2.6

**Comment by Anahkiasen** [comment]
Hm not sure there is much I can do, this is more of an issue with `illuminate/console`. I can't update to `illuminate/console:~5.0` as it includes a lot of breaking changes, best solution would be to ask for the Symfony components to be bumped to 2.6 on Laravel's end

**Comment by marcovtwout** [comment]
Reposted: https://github.com/laravel/framework/issues/7004

**Comment by Anahkiasen** [comment]
Note that alternatively you can also install Rocketeer globally or use the PHAR

**Comment by GrahamCampbell** [comment]
I agree this is a bit of a bummer. I want laravel 5 to use `~2.3` and ~2.5` for the various symfony components but Taylor doesn't agree with me. What do you two think about that change?
