### ISSUE TITLE
Deployment to localhost without ssh overhead

### ISSUE THREAD

**Issue by mabrahamde** [rocketeers/rocketeer#402]
I am wondering if it would be possible to deploy a project to localhost without the overhead of ssh. 
I like the idea of executing rocketeer directly on the server(s). In this case you do not need to connect via ssh. You can execute all commands directly. 

I do not want to store the private keys on the server.

Any suggestions?

**Comment by Anahkiasen** [comment]
So you want to ping the server and then the server uses Rocketeer to deploy a new release, locally?

**Comment by mabrahamde** [comment]
This would be one possible mechanism to trigger the release. However i just want rocketeer to run locally and deploy to localhost without using ssh.

**Comment by Anahkiasen** [comment]
`Rocketeer\Rocketeer` has a `local` switch that will execute all tasks and commands in local instead of connection anywhere, is that what you mean? That's how [Satellite](https://github.com/rocketeers/satellite/blob/master/src/Abstracts/AbstractRocketeerCallerCommand.php) does it

**Comment by mabrahamde** [comment]
thanks, that's what i am looking for.

**Comment by ShonM** [comment]
How about a way to reach that from the CLI? I'm not sure I see anything. For now I just in_array on argv and add it myself directly from bin/rocketeer, but an official flag would be nice. I can see how it might complicate some things though :(

**Comment by Anahkiasen** [comment]
I'm not sure the use case is wide enough for it to warrant a flag while we already have quite an amount of them but I'll keep it in mind for 2.1. What is your case per example??

**Comment by ShonM** [comment]
Something like Sattelite, actually! Its focused on just one application though, and each node reports back to a master for state and coordination.

**Comment by ShonM** [comment]
Oh that doesn't explain it... I just wanted to test some things before I kept going. That's all. So for now a custom bin works a treat :)
