### ISSUE TITLE
Multiple log files for one command

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#404]
I want to include the exact timestamp in my logfiles (otherwise running it multiple times the same day overwrites my log), so I formatted it like this:

```
return sprintf('%s-%s-%s-%s.log', $connections->getConnection(), $connections->getStage(), date('Ymd'), date('His'));
```

However, when I run a `rocketeer deploy` just once, this results in multiple log files:

```
Execution time: 13.531s
Saved logs to S:/www/dgbc_qa/.rocketeer\logs/staging--20150116-092154.log
Saved logs to S:/www/dgbc_qa/.rocketeer\logs/staging--20150116-092157.log
Saved logs to S:/www/dgbc_qa/.rocketeer\logs/staging--20150116-092206.log
Saved logs to S:/www/dgbc_qa/.rocketeer\logs/staging--20150116-092207.log
```

**Comment by Anahkiasen** [comment]
I think this is fixed on develop, can you try? Or are you already using the develop branch?

**Comment by marcovtwout** [comment]
I have to use the the latest 2.x-release until https://github.com/rocketeers/rocketeer/issues/403 is solved ;)

**Comment by marcovtwout** [comment]
Maybe it's time for a new (minor) release by the way?

**Comment by marcovtwout** [comment]
Yes, this was fixed on develop (should have tried that first).
