### ISSUE TITLE
Cannot install svn dependencies that require authentication

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#405]
Using latest develop, I get the following error message on `rocketeer deploy --verbose`:

```
|-- Dependencies (Installs or update the dependencies on server)
|---- Dependencies/Polyglot (Runs all of the above package managers if necessary)
|------ Dependencies/Composer (Installs dependencies with Composer)
$ cd /data/test/releases/20150116093711
$ /home/user/bin/composer install --no-dev --prefer-dist
[user@host] (staging) Installing dependencies
[user@host] (staging) - Installing privatevendor/xxx (3.0.0)
[user@host] (staging) Checking out /tags/3.0.0/@281
[user@host] (staging) [RuntimeException]

  Package could not be downloaded, can not ask for authentication in non interactive mode
[user@host] (staging) install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--n
o-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optim
ize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]
[user@host] (staging)
|=====> An error occured: "Composer could not install dependencies"
```

When I run `/home/user/bin/composer install --no-dev --prefer-dist` directly on the host, I am correctly prompted for authentication details:

```
 /home/user/bin/composer install --no-dev --prefer-dist
Loading composer repositories with package information                                                                           Installing dependencies 
- Installing privatevendor/foo (3.0.0)
    Checking out /tags/3.0.0/@281
The Subversion server (https://svn.xxx.nl/svn/foo) requested credentials:
Username:
```

Is Rocketeer 'blocking' the interactive mode somehow?

**Comment by Anahkiasen** [comment]
It is because Rocketeer has currently no way to pass you questions asked by the server and send back the answers. You can see the option being passed [here](https://github.com/rocketeers/rocketeer/blob/master/src/config/strategies.php#L33). Is there no way in Composer to store the credentials somewhere?

**Comment by marcovtwout** [comment]
Yes: it is possible to pass or store these (globally) with the http-basic config option: https://getcomposer.org/doc/04-schema.md#config

What confused me here, is that Rocketeers hook you linked to includes `'--no-interaction' => null`, which suggests it can be removed to allow prompts.

**Comment by Anahkiasen** [comment]
Well you _can_ remove it, you should have the file I linked in your config. Just not sure it would work, the deployment would probably hang waiting for you to input the username while you can't actually do so

**Comment by marcovtwout** [comment]
When I remove it, it seems interactive mode is (automatically?) disabled somehow, as you can see in the top post:

`Package could not be downloaded, can not ask for authentication in non interactive mode`

**Comment by Anahkiasen** [comment]
This is actually a feature I'll implement at some point (see #283 ) but it'll take some major changes internally

**Comment by Anahkiasen** [comment]
Ah yes Composer might be smart enough to block the prompt if it recognizes you can't type anything (because this is code executed by a third party, not an actual user), good to know
