### ISSUE TITLE
Cannot update existing svn release

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#406]
Using latest develop, deployment is succesful. But when I try `rocketeer update --verbose`:

```
| Update (Update the remote server without doing a new release) [~2.47s]
|-- Primer (Run local checks to ensure deploy can proceed)
|-- Deploy/Clone (Clones a fresh instance of the repository by SCM)
Pulling changes
$ cd /data/www/releases/20150116112717
$ svn status -q | grep -v '^[~XI ]' | awk '{print $2;}' | xargs svn revert
$ svn up --non-interactive --username="user" --password="xxx"
[[user@host]] (staging) svn: E205001: Try 'svn help revert' for more information
svn: E205001: Not enough arguments provided
```

This line fails: `$ svn status -q | grep -v '^[~XI ]' | awk '{print $2;}' | xargs svn revert`
And subsequently, the svn-up is not performed.

The error occurs when there is nothing to svn-revert. It is fixed by adding the `--no-run-if-empty` option:

`svn status -q | grep -v '^[~XI ]' | awk '{print $2;}' | xargs --no-run-if-empty svn revert`
http://stackoverflow.com/questions/8296710/ignore-empty-result-for-xargs

**Comment by Anahkiasen** [comment]
Could you send a pull request for this to the develop branch?

**Comment by marcovtwout** [comment]
Thanks.
