### ISSUE TITLE
Logging: CLI -> File?

### ISSUE THREAD

**Issue by ShonM** [rocketeers/rocketeer#412]
I might be alone on this one but, I think it would be great to have the CLI verbatim in the log files. It helps explain what stage Rocketeer is on (not stage like prod but part of the deploy process) and massively helps when debugging (so far).

Maybe there's a way to do this already? I'm going to look if this doesn't get attention in a day or so. Not hugely important for now :)

**Comment by Anahkiasen** [comment]
You should have logs of each deploy in `.rocketeer/logs` (or storage/logs in Laravel), is that not working properly?

**Comment by ShonM** [comment]
Sorry this took so long to get. I wanted to set up a fresh environment and grab some fresh logs for this.

From a four-server deploy:
```
Saved logs to /Users/shonm/Sites/Com/deploy/.rocketeer/logs/local-full-dev-20150120_10:25:41.log
Saved logs to /Users/shonm/Sites/Com/deploy/.rocketeer/logs/local-full-dev-20150120_10:27:50.log
Saved logs to /Users/shonm/Sites/Com/deploy/.rocketeer/logs/local-full-dev-20150120_10:30:12.log
Saved logs to /Users/shonm/Sites/Com/deploy/.rocketeer/logs/local-full-dev-20150120_10:32:15.log
```

With this log config:
```
return sprintf('%s-%s-%s.log', $connections->getConnection(), $connections->getStage(), date('Ymd_H:i:s'));
```

Here's the log content of all four: https://gist.github.com/ShonM/8404826be33fe44c982d. What strikes me is that there's a distinct lack of connection information here. In the CLI not only do I get that, but I get to see the terminal prompt as well which reads the user, hostname, and some other information that would be quite handy to have all in just one log.

The way I thought this was supposed to work was essentially the CLI-shown output going straight into a file sans color. Is that not it?

**Comment by Anahkiasen** [comment]
I actually never noticed that but you're right, the output is gathered from the command, logged as is, and *then* passed to the Connection instance which is what adds the connection handle. Will change that

**Comment by Anahkiasen** [comment]
Should have more informations on develop now

**Comment by ShonM** [comment]
What about lines like these? http://cl.ly/image/2e381X1N2s1I

The logs do indeed look much better. Thank you, that helps tons :)
