### ISSUE TITLE
Host(name) in ConnectionsHandler::getHandle()?

### ISSUE THREAD

**Issue by ShonM** [rocketeers/rocketeer#416]
I'd love for this to show on the logs. Right now it's "connection/index/stage" (`local/1/dev` for example), and I think it would be useful to change that to "connection/host/stage" or even "connection/stage/host" so it reads like `prod/prod/name.com`

I attempted to implement this myself but it's being reset and I haven't dug in to find out why quite yet. Here's what I tried:
 - Replace this: https://github.com/rocketeers/rocketeer/blob/da370db97039812074fcc16270738b4731ae2288/src/Rocketeer/Services/Connections/ConnectionsHandler.php#L78
 - With this: `$server     = $server ?: Arr::get($this->getAvailableConnections(), $connection.'.servers.'.$this->currentServer.'.host');`

The logs show the first host properly, but not after that (they revert to using the index-based output).

**Comment by Anahkiasen** [comment]
Hm that's a good idea yeah, server indexes are not the easiest thing to understand when you see per example `production/0` or `production/1`, will work on that

**Comment by ShonM** [comment]
This works perfectly, thank you Maxime! :+1:  :)
