### ISSUE TITLE
Multiple deployments?

### ISSUE THREAD

**Issue by jbrooksuk** [rocketeers/rocketeer#419]
I've read through the documentation and issues, but found no mention of deploying multiple sites to one server?

We have a couple of Apache sites setup on one server which I want to get deploying after being pushed to GitHub (they're all private). Does Rocketeer support this? It seems like it's made for one application only?

**Comment by Anahkiasen** [comment]
It is indeed, you might want to use [Satellite](https://github.com/rocketeers/satellite) but it's still not officially released yet, will be in the near future.

**Comment by jbrooksuk** [comment]
Ok, so Rocketeer does support more than one application? And Satellite is a management system for it?

**Comment by Anahkiasen** [comment]
Rocketeer supports more than one application *but* you can only use it _from_ an application itself, ala Capistrano. Satellite is setup on the server and is indeed a management system for all the applications that are deployed on it, thus allowing you from your hook to do something like `satellite deploy foo && satellite deploy bar`. Features of Satellite are currently very limited but as I said it's still being worked on
