### ISSUE TITLE
--no-interaction ?

### ISSUE THREAD

**Issue by ShonM** [rocketeers/rocketeer#421]
Just as the title says, maybe this could get added as an option? The use case is just that Rocketeer keeps asking me for credentials it doesn't need :P Repo user/pass and password for agent-authed connections - which I understand I might be alone in using for now. Tried debugging a bit but it looks like it needs to be re-architected a bit to support a wider array of possible configurations.

**Comment by Anahkiasen** [comment]
2.1.0 will have multiple types of credentials including [never prompts](https://github.com/rocketeers/rocketeer/blob/develop/src/config/config.php#L35) but this is still being worked on

**Comment by Anahkiasen** [comment]
That being said Rocketeer is based off Symfony Console so `--no-interaction` should already be there nevertheless

**Comment by ShonM** [comment]
Oh what do you know, that didn't even occur to me. It's too early to be filing issues :)
