### ISSUE TITLE
On develop: "Unable to clone the repository"

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#424]
Using latest develop, running `rocketeer deploy` returns some strange behavior. Snippets from the console:

```
svn co repository..
(..add..add..add..)
Checked out revision 491.
staging |===> An error occured: "Unable to clone the repository", while running:
(..)
(..ending with..)
[@staging] The tasks queue was canceled by task "Deploy"
```

It looks like the CloneStrategy? thinks an error occured, while checkout went fine.
Also, the task queue was canceled because of this error?

**Comment by Anahkiasen** [comment]
Well it should cancel the queue if it's unable to clone the repository, that makes sense. Can you run with `-vvv` see a little more info about what it executed that failed? And try to run the command yourself on the server see if it works then?

**Comment by marcovtwout** [comment]
The output with -vvv is no different, and the command works fine on the server. There is no error, only Rocketeer/CloneStrategy? thinks there is.

```
svn co repository..
(..add..add..add..)
Checked out revision 491.
```

**Comment by Anahkiasen** [comment]
Hm weird but ok, will investigate see what I find

**Comment by Anahkiasen** [comment]
Fixed

**Comment by marcovtwout** [comment]
Confirmed, thanks.
