### ISSUE TITLE
Warning when --no-interaction causes a prompt not to occur

### ISSUE THREAD

**Issue by ShonM** [rocketeers/rocketeer#425]
Things like this: `No password is set for [local-full/web.c.com], please provide one:`

Would be nice to display this, but replacing "please provide one" with "but non-interactive mode is on"

I will PR this if it's not snapped up otherwise :)

**Comment by ShonM** [comment]
That displays a single warning, but doesn't explain *what* is being prompted for which is my goal. Would you take a PR for that still?

**Comment by Anahkiasen** [comment]
Should be an easy tweak, will add something quickly
