### ISSUE TITLE
Debugging "Unable to connect to remote server" on rocketeer check

### ISSUE THREAD

**Issue by ts** [rocketeers/rocketeer#427]
Not sure where to look to determine why rocketeer is unable to connect to a remote server. I'm able to connect just fine using `ssh deploy@staging.example.com`. I've tried with a blank `key` entry in the connection array, as well as the absolute path.

Running `rocketeer check -vvv` doesn't give me anything useful in trying to solve the connection problem.

Thoughts anyone?

**Comment by Anahkiasen** [comment]
Is this on 2.0 or 2.1-dev? If the former, can you test with the `develop` branch?

**Comment by ts** [comment]
Looks like `Rocketeer version 2.0.4`. I'll try pulling down `2.1-dev` and see where I end up.

**Comment by ts** [comment]
The new prompt for passphrase seemed to kick something into gear and things are connecting just fine. I'd imagine it'll work on `2.0.4` now as well. Thanks @Anahkiasen
