### ISSUE TITLE
Disable composer

### ISSUE THREAD

**Issue by chadrien** [rocketeers/rocketeer#435]
Hi, I've seen that commit 851a21ff5 is supposed to make us able to disable composer execution on deployment, but there is no associated docs nor documention, so how are we supposed to do it?

**Comment by Anahkiasen** [comment]
Wow, that's an old commit there. What version are you on?

**Comment by chadrien** [comment]
dev-master

**Comment by Anahkiasen** [comment]
Ok – then in theory you should be able to set `null` as your Dependencies strategy in strategies.php and that should skip it
