### ISSUE TITLE
SSH Agent never works for me.

### ISSUE THREAD

**Issue by cerw** [rocketeers/rocketeer#436]
Hi 
I have deployed via capistrano and via rocketerr, whatever i tried ssh-agent option never works in php 

I have debug the and found out that you must have RSA key to have key option working But even then agent always failed to connect? It does not even connect to remote server. 

How can I debug this more ?

thanks

**Comment by aftabnaveed** [comment]
it seems like the private key you are trying to connect with does not have matching public key stored on server,  can you paste some more info?    this <code>ssh -v user@hostname </code> will give you some useful information.

**Comment by cerw** [comment]
That's def not the case as I can ssh into the server.

**Comment by Anahkiasen** [comment]
Agent forwarding was not supported before so the `agent` option was actually half-implemented. It's currently fully implemented in Rocketeer 3 (the dev branch)
