### ISSUE TITLE
Troubleshooting - opcache + nginx

### ISSUE THREAD

**Issue by austenc** [rocketeers/rocketeer#437]
When utilizing nginx and php-fpm, the troubleshooting section in the docs unfortunately doesn't work. In a nutshell, `php -r "opcache_reset()"` will only flush the CLI cache, not FPM. There are generally two acceptable solutions:

* create a web-accessible script that calls `opcache_reset()` and hit it with CURL or something
* add this to nginx server configuration, [as described here](https://github.com/zendtech/ZendOptimizerPlus/issues/126):
```
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
fastcgi_param DOCUMENT_ROOT $realpath_root;
```
Currently the fix described in rocketeer's troubleshooting doesn't really do anything if you're using nginx and php5-fpm -- just wanted to make you aware.

**Comment by Anahkiasen** [comment]
Hm didn't know that. Can you do a PR to the docs with that information?

**Comment by austenc** [comment]
I certainly can. Should get to it this afternoon, thanks!

**Comment by reinink** [comment]
Isn't the preferred way of solving this to simply do a `server php-fpm reload`? I know that comes with it's own permission issues, but that's maybe another recommendation to put on the troubleshooting page.

**Comment by austenc** [comment]
@reinink doesnt that restart the process though? If there are users online at the time of deploy that would defeat the purpose of the symlink deploy.. Is there a difference between the command you listed and restarting the php-fpm service?

**Comment by reinink** [comment]
@austenc I don't think so, I believe `reload` is graceful, meaning no interruption in service. For more information, checkout [this screencast](https://serversforhackers.com/video/enhancing-envoy-deployment) by @fideloper which explains this technique in a little more detail.

**Comment by austenc** [comment]
@reinink Finally got a chance to do some testing on this myself. I put the command `sudo service php5-fpm reload` in my `deploy.after` hook and it did not reload / clear opcache to show the latest version of the files. If I ssh into the server and run that reload command manually after I've deployed then it shows the latest version of the files like you'd expect.

Have you been able to get the `service php5-fpm reload` command working properly in the context of the rocketeer deploy?

**Comment by fideloper** [comment]
You need "sudo" abilities to run that - does your user have permission to use sudo without a password to run that command? The linked video above explains how! :D

**Comment by austenc** [comment]
I did use sudo in this case.. But I'll watch the video in its entirety and try again. I'll be happy to send a PR to rocketeer's docs after trying again too. Thanks @fideloper

**Comment by barryvdh** [comment]
So what is the 'correct' way to handle this?

http://rocketeer.autopergamene.eu/#/docs/docs/VI-Help/Troubleshooting
https://github.com/zendtech/ZendOptimizerPlus/issues/126#issuecomment-24020445
> To fix the problem in this case, add the lines below to your nginx server configuration.
>
```
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
fastcgi_param DOCUMENT_ROOT $realpath_root;
```
>Usually the file is located at /etc/nginx/fastcgi.conf.

Or https://serversforhackers.com/video/enhancing-envoy-deployment

```
sudo visudo

%www-data ALL=(ALL:ALL) NOPASSWD:/usr/sbin/service php5-fpm restart,/usr/sbin/service php5-fpm reload

sudo service php5-fpm reload
```
With an `deploy.after` hook?

**Comment by fideloper** [comment]
To clarify, I'm not sure that reloading php-fpm clears the opcache (I'm not sure about restarting either).

What it does do is tells PHP-FPM to stop processes once they finish their next request (that's the graceful part of reloading, versus restarting which just kills the processes) and respawn them after grabbing any updates in configuration.

This includes stopping processes that may otherwise have handled further requests (via the [max_requests](http://php.net/manual/en/install.fpm.configuration.php#pm.max-requests) configuration which has a process "live" until it handles x number of requests).

**Comment by fideloper** [comment]
I think that thread linked in the original post here says it all: https://github.com/zendtech/ZendOptimizerPlus/issues/126

Reloading PHP-FPM appears not to be a  solution in regards to clearing  opcache.

**Comment by barryvdh** [comment]
Okay, but as far as I can see, Envoyer actually does use this. And Forge provides a recipe:
> Enable PHP5-FPM Reload Without Password
> `echo "forge ALL=NOPASSWD: /usr/sbin/service php5-fpm reload" > /etc/sudoers.d/php5-fpm`

And adding `sudo /usr/sbin/service php5-fpm reload` correctly fixes the symlinks after deploy :)

**Comment by mreschke** [comment]
For me, using latest Debian Jessie php5-fpm version, the `reload` does indeed clear the opcache and all my stale symlink deployment issues!  My sudo has NOPASSWD and I don't call it from rocketeer directly.  I have rocketeer call a `/usr/local/bin/sync-webservers` bash script on `web1` which does an rsync + sudo /etc/init.d/php5-fpm reload on all other servers in the farm.  Works well.
