### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#438]
There have been many fixes since 2.0.4, could you make a new incremental release?

**Comment by Anahkiasen** [comment]
I'll try to see if there is a point I can cut off and make a 2.0.5 but since the next release [is major](https://github.com/rocketeers/rocketeer/pull/432) all the bugfixes are mixed with features that aren't yet finished so I can't release that yet

**Comment by marcovtwout** [comment]
Yes, I posted because I saw that coming, and I would appreciate a final stable release for 2.x. :)

**Comment by marcovtwout** [comment]
Could you split off a new release? 2.0.4 contains a few bugs that are now fixed in develop, but latest develop is often too unstable.

**Comment by Anahkiasen** [comment]
Can you tell me which fixes in particular you'd like to see backported? Cause I tried to see at what point develop became breaking and, well, it's pretty early, so I'll probably need to do it manually

**Comment by Anahkiasen** [comment]
Aight so I mishmashed a bunch of bugfixes together with the power vested in me by git cherry-pick (thank god I do small commits), 2.0.5 is now tagged with the following bugfixes:

````
- Fixed a bug where trying to use an invalid connection would just fallback silently to the default one
- Fixed missing dependency in generated PHARs
- Fixed symlink issues on non-GNU/Linux OSes
- Fixed paths defined in `paths.php` sometimes being ignored
- Fixed some jobs using the wrong server on multiserver connections
- Fixed an issue where polyglot strategies would keep running after one of their child failed
- Fixed an issue where the logs filename would get recomputed every call
```

**Comment by aftabnaveed** [comment]
cool, I used it for testing purposes yesterday, and I was really impressed how it was able to run deployment in parallel to multiple servers, though I noticed one minor issue with clean up which I will verify today and if that still exist I will create an issue. 

just to give you an overview, I tried rocketeer cleanup --clean-all, when I checked the code it should not clean the current release, but for some reason it did and broke the current symlink, I will try to reproduce that and then let you know.
