### ISSUE TITLE
Dependency issue with illuminate/console

### ISSUE THREAD

**Issue by tuupola** [rocketeers/rocketeer#441]
This is more of an issue with `illuminate/console` but a heads up for you here. Commands below fail because `illuminate/console` has locked the dependency of `symfony/console` to minor version number `2.5.*`. I am pretty sure Symfony semantic versioning could be trusted and `illuminate/console` should use `~2.5` instead.
 
```
$ composer require symfony/console
$ composer require anahkiasen/rocketeer
```

Are any features of `illuminate/console` used or would vanilla `symfony/console` be enough?

**Comment by tuupola** [comment]
Apparently locking into specific minor version is considered as feature in Laravel.

https://github.com/illuminate/console/commit/061ade4d7448a6e5df8bb878e2252fc467739adc

**Comment by GrahamCampbell** [comment]
Yeh, Taylor doesn't want to budge on locking the minor version of symfony components.
