### ISSUE TITLE
Any way to create a variable based on connection/stage?

### ISSUE THREAD

**Issue by JCMais** [rocketeers/rocketeer#442]
Is it possible to have a variable which value can be modified based on the current connection/stage?

**Comment by Anahkiasen** [comment]
What are you trying to do more precisely?

**Comment by JCMais** [comment]
I have an API I need to request after the deploy is finished, the API url depends upon the connection (production server vs staging server). So I want to get the correct url in the task that fires the request.

**Comment by Anahkiasen** [comment]
You can do `$this->connections->getConnection()` to get the name of the current connection, would that work? There a lot of methods on the ConnectionsHandler you could use for that matter

**Comment by JCMais** [comment]
Yes, that would work. What would be really interesting is that if we could set such variables inside a configuration file.

So something like the following would be possible:

    //.rocketeer/connections/production/variables.php
    return array{
        'api_endpoint' : 'http://example.com/api/'
    }

    //.rocketeer/connections/production/variables.php
    return array{
        'api_endpoint' : 'http://staging.example.com/api/'
    }

    //inside some task
    $task->getVariable( 'api_endpoint' );

I will leave this here as a feature request. Thank you!

**Comment by Anahkiasen** [comment]
Well actually you can pretty much already do that, just add your variable anywhere in the config files, per example in `config.php`:

```php
'foo' => 'bar',
```

And then you can do `$this->getOption('foo')`

**Comment by JCMais** [comment]
That was exactly what I wanted, thanks!
