### ISSUE TITLE
Backport fixes into 2.0.x

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#446]
Following on https://github.com/rocketeers/rocketeer/issues/438

Thanks for making a new release. Could you also backport the following fixes into 2.0.x (.6)?

- Update-command fails for svn: https://github.com/rocketeers/rocketeer/pull/408
- Prompt for keyphrase: https://github.com/rocketeers/rocketeer/issues/190
- Wrong version number: https://github.com/rocketeers/rocketeer/blob/2.0.5/src/Rocketeer/Rocketeer.php#L29

**Comment by Anahkiasen** [comment]
Hm the prompt for ssh keyphrase is not possible, it's a big change to the CredentialsGatherer and requires the new credential types which are a BC change

**Comment by marcovtwout** [comment]
Ah, too bad, I thought that change was backwards compatible according to your comment: https://github.com/rocketeers/rocketeer/issues/190#issuecomment-67255326

**Comment by Anahkiasen** [comment]
Well it's more or less compatible, ie. it won't literally break but it'll start prompting everyone for stuff it didn't use to ask them if they're not aware and don't update their configurations which isn't the nicest thing.

**Comment by Anahkiasen** [comment]
Tagged 2.0.6 with the version constant and SVN fix
