### ISSUE TITLE
2.0.5 const VERSION = '2.0.4'

### ISSUE THREAD

**Issue by mikemunger** [rocketeers/rocketeer#447]
Hello,

I was just reviewing your 2.0.5 tagged release, and noticed from cli running the binary with -v was printing out "Rocketeer version 2.0.4" even though composer just informed me it updated to v2.0.5. Just thought you might want to know about it.

Thank you

rocketeer/src/Rocketeer/Rocketeer.php

const VERSION = '2.0.4';

in tagged branch 2.0.5

**Comment by Anahkiasen** [comment]
Yeah saw that, will track in #446
