### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by fedeisas** [rocketeers/rocketeer#449]
I'm trying to implement Rocketeer as my deployment tool.

Something I miss from capistrano is roles, like:
"Restart workers only on XX machine" or "Run migrations only on YY machine"

Is there any way to do this with the current codebase? Should I try to implement it and PR?

Thanks.

**Comment by Anahkiasen** [comment]
That's implemented on 3.0-dev but not present in 2.0 no

**Comment by fedeisas** [comment]
Awesome! Any ETA on 3.0? Thanks!

**Comment by Anahkiasen** [comment]
Not yet no, it's a major release and contains breaking changes so needs more work on it before being stable
