### ISSUE TITLE
Composer update fails on phpseclib

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#450]
Trying to update to latest develop. This also fails when trying an older develop that doesn't require this phpseclib yet, appearantly Composer cannot tell the difference:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for anahkiasen/rocketeer dev-develop#80d32227d0317e93549fa31a1e74672723ef69bd -> satisfiable by anahkiasen/rocketeer[dev-develop].
    - anahkiasen/rocketeer dev-develop requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

Config:
````
"anahkiasen/rocketeer": "dev-develop",
or:
"anahkiasen/rocketeer": "dev-develop#80d32227d0317e93549fa31a1e74672723ef69bd",
```

**Comment by Anahkiasen** [comment]
You need to require `3.0.*@dev` for now

**Comment by marcovtwout** [comment]
Rocketeer 3.0.*@dev?

```
Problem 1
    - Installation request for anahkiasen/rocketeer 3.0.*@dev -> satisfiable by anahkiasen/rocketeer[3.0.x-dev].
    - anahkiasen/rocketeer 3.0.x-dev requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
```

**Comment by Anahkiasen** [comment]
Do you have `"minimum-stability": "dev"` in your composer.json?

**Comment by marcovtwout** [comment]
3.0.* or dev-develop shouldn't matter. Anyways, appearantly I have to set the dev-flag for phpseclib separately. I solved it like this:

```
"anahkiasen/rocketeer": "dev-develop",
"phpseclib/phpseclib": "@dev"
```

This way we don't get the development version of every single requirement, which is a bit unnecessary.

**Comment by GrahamCampbell** [comment]
`"phpseclib/phpseclib": "@dev"` Noooooo. Never use unbound versions!

`"anahkiasen/rocketeer": "dev-develop"` OMG! Even worse. Always use a version constraint!

**Comment by marcovtwout** [comment]
Why would I use a version constraint when I -need- to require the development version?

**Comment by GrahamCampbell** [comment]
@marcovtwout. You seem to be not be understanding versions constraint at all. Stability has nothing to do with it whatsoever.

This is what you should have done:

```json
{
    "require": {
        "anahkiasen/rocketeer": "3.0.*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by GrahamCampbell** [comment]
> 3.0.* or dev-develop shouldn't matter.

Totally untrue!

**Comment by marcovtwout** [comment]
I agree your points are valid in general for applications that only use Rocketeer, but not in my particular case:

- There is no carved-in-stone rule that you always in every case have to use a version constraint. I use Rocketeer for development -on- Rocketeer.
- Specifying a minimum stability for a specific library `"phpseclib/phpseclib": "@dev"` helps me keep track of -which- library does not have a usable release yet.

If you still disagree, please enlighten me with some actual arguments specific to this use case.

**Comment by GrahamCampbell** [comment]
But what that means is in 2 years time, if someone were to use that composer.json file, they'd be totally f***ed, but if you'd used a version constraint, they'd likely be mainly fine.

3.0.x-dev will not always be dev-develop. That's my point, and `@dev` is never acceptable - that's exactly the same as writing `*`.

**Comment by GrahamCampbell** [comment]
Writing `"phpseclib/phpseclib": "3.0.*@dev"` is totally ok, but never just `@dev`.
