### ISSUE TITLE
Debugging "Unable to connect to remove server"

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#451]
I saw a few older issues that run into the same problem. If there is a fault in the login credentials, Rocketeer returns:

```
  [Rocketeer\Exceptions\ConnectionException]
  Unable to connect to remote server.
  With credentials:
     (..)
```

Unfortunately, this is not always enough to debug the specific issue when the credentials seem correct. This may depend on the library you are using, but is there a way to improve the debug output? In my specific case, I am supplying a DSA-key, which phpseclib does not support: https://github.com/phpseclib/phpseclib/issues/216

Also, could you document this key type restriction somewhere?

**Comment by Anahkiasen** [comment]
Yup will do

**Comment by ShonM** [comment]
I was using this earlier (in case it helps) https://github.com/laravel/framework/pull/6989

Glad I didn't waste the time resubmitting just for it to get deprecated :)

**Comment by JanisE** [comment]
Same here. Was using DSA and got a general "Unable to connect to remote server." message. (Got the same problem with using password, but probably because got configuration mixed up in a hurry.)

**Comment by Anahkiasen** [comment]
Connections in Rocketeer 3 are inherently Flysystem SFTP instances so login and errors are handled by them. The errors are a bit more specific although I do not see one specifically about DSA keys but I'll try to see if I can make a PR to their repository with it
