### ISSUE TITLE
Composer options missing on deploy

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#452]
Using latest development: has the Composer execution hook syntax changed?

In strategies.php
```
'composer'     => array(
		'install' => function (Composer $composer, $task) {
			return $composer->install([], ['--no-interaction' => null, '--no-dev' => null, '--prefer-dist' => null, '--optimize-autoloader' => null]);
		},
```

When I try rocketeer deploy, it simply runs `composer install` without any of these options.

**Comment by Anahkiasen** [comment]
Yes, this config option has been removed in favor of the options and flags system. It's still been worked on so syntax is not final but basically, you'd now do in tasks.php per example:

```php
Rocketeer::configureStrategy(['Dependencies', 'Composer'], array(
  'flags' => array(
    'install' => ['your' => 'flags'],
  ),
));
```

As I said, there'll probably be an easier way later but currently that _should_ work

**Comment by marcovtwout** [comment]
Alright.

While you're working on it, quick suggestion. Commands without parameters could also be specified without a key, for example:

For example: `['on' => 'staging', 'no-dev']`
Instead of: `['on' => 'staging', 'no-dev' => null]`

When processing the install array, you could simply check is_numeric on the array key.

**Comment by Anahkiasen** [comment]
To be honest I thought that worked already but yeah, will add that :d
