### ISSUE TITLE
Local mode gets busted, yo

### ISSUE THREAD

**Issue by ShonM** [rocketeers/rocketeer#457]
https://github.com/rocketeers/rocketeer/blob/develop/src/Rocketeer/Traits/BashModules/Core.php#L80

This will exit local mode after a locally local command. My fork is silly otherwise this would be a PR. Working on cleaning up so I can submit more of those...

**Comment by Anahkiasen** [comment]
That's because `onLocal` is made to run one command in local, not everything. To run everything in local Rocketeer has a global local mode

**Comment by ShonM** [comment]
Totally! I set that, too. Same issue, at least for me.
