### ISSUE TITLE
Global install does not work (via composer global require).

### ISSUE THREAD

**Issue by JerseyMilker** [rocketeers/rocketeer#461]
Could not load package anahkiasen/rocketeer in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^4.2.7: Invalid version string "^4.2.7"

**Comment by Anahkiasen** [comment]
Do `composer self-update`, will work after that

**Comment by JerseyMilker** [comment]
Hmm, different error, but it's still not finishing.  http://hastebin.com/raw/ajosogibaw

**Comment by Anahkiasen** [comment]
What dependencies do you have? Seems just a basic conflict with symfony/console

**Comment by JerseyMilker** [comment]
http://puu.sh/gkTl2/18c257a91d.png

**Comment by JerseyMilker** [comment]
Still not able to install via composer, globally or within Laravel 5 project :(

**Comment by Anahkiasen** [comment]
Just use the PHAR version, you can install it globally too, see the main README

**Comment by JerseyMilker** [comment]
Okay thanks.  Should be able to at least composer require within L5 project though.

**Comment by Anahkiasen** [comment]
In the next version of Rocketeer most of the illuminate components have been swapped for something else. The rest will be updated to use the 5.0 components yes but that'll break 4.2 compatibility (so if you use 4.2 you'll have to use Rocketeer 2 too).

**Comment by JerseyMilker** [comment]
Right on thanks. When is Rocketeer 2 coming? ;)

**Comment by Anahkiasen** [comment]
Well Rocketeer 2 is already the current stable, 3 is still in the works, lots of other features needed for it too. You can check the 3.0 milestone if you want https://github.com/rocketeers/rocketeer/milestones/3.0.0

**Comment by JerseyMilker** [comment]
Oh I misread you. Can't wait for 3.0 then!
