### ISSUE TITLE
Deploying to local machine

### ISSUE THREAD

**Issue by allantatter** [rocketeers/rocketeer#463]
Is there a possibility to disable SSH'ing to remote server from config files in order to deploy onto the same machine?

**Comment by dizews** [comment]
+1

**Comment by Anahkiasen** [comment]
Hm yes and no, Rocketeer can and does, but you can't. At least not yet. What about if you set the host to `localhost` it uses the `LocalConnection` class Rocketeer uses internally to execute local commands.

**Comment by dizews** [comment]
@Anahkiasen even if I set host to localhost rocketeer try to connect by ssh.

**Comment by Anahkiasen** [comment]
No I know, as I said, it's not possible at the moment, but were I to implement it, it would be through setting the host to localhost

**Comment by blafasel42** [comment]
+1 from me. any news here?

**Comment by thiagotalma** [comment]
+1

**Comment by cronfy** [comment]
+1
