### ISSUE TITLE
Composer errors ignored

### ISSUE THREAD

**Issue by barryvdh** [rocketeers/rocketeer#466]
When Composer fails on deploying, the deployment isn't aborted but continues.
Because composer fails, the vendor files are missing so the website will crash.

Rocketeer does detect the error, but proceeds anyway. This happens for example by a missing requirement (like Boris requiring extra extensions in 1.0.10 vs 1.0.8) or older composer version (not understanding ^ sign).

Example error:

    [user@host] (production) Your requirements could not be resolved to an installable set of packages.
    [user@host] (production) Problem 1 [..]
    production/0/dev        |=====> An error occured: "Composer could not install dependencies"
    [..]
    production/0/dev        |=> Successfully deployed release 20150306114046

**Comment by Anahkiasen** [comment]
I thought that was fixed, or maybe it's only fixed on 3.0-dev, what version is that?

**Comment by barryvdh** [comment]
`2.0.6`

**Comment by Anahkiasen** [comment]
Is this a custom task, Polyglot dependencies strategy or Php strategy?

**Comment by barryvdh** [comment]
THis is just a regular deploy.

    // Which strategy to use to install your application's dependencies
	'dependencies' => 'Polyglot',

**Comment by barryvdh** [comment]
Much better :)

Should the after task still run though?

    |=====> An error occured: "Composer could not install dependencies"
    |-- Closure (php artisan assetic:build) fired by deploy.after [~4,55s]
    $ cd /home/user/domains/mydomain.com/application/releases/20150310093616
    $ php artisan assetic:build
    The tasks queue was canceled by task "Deploy"

**Comment by Anahkiasen** [comment]
It's bound to Dependencies or Deploy?

**Comment by barryvdh** [comment]
// Tasks to execute after the core Rocketeer Tasks
	'after'  => array(
		'setup'   => array(),
		'deploy'  => array('php artisan assetic:build'),
		'cleanup' => array(),
	),

**Comment by Anahkiasen** [comment]
welp nope dats weird. Can you open a separate issue for it so I don't forget?

**Comment by peshkov3** [comment]
Anahkiasen, have you included this correction to the rocketeer.phar file? I tried to reinstall rocketeer.phar file with command: wget http://rocketeer.autopergamene.eu/versions/rocketeer.phar,  but this problem appeared again.
