### ISSUE TITLE
permission denied to create folder 

### ISSUE THREAD

**Issue by vipin733** [rocketeers/rocketeer#467]
I try to follow  http://richardhawthorn.com/?p=148 tutorial but when i try to deploy its saying errors 
can not create directory ubuntu@52.74.xx.xxx <production> permission denied

**Comment by Anahkiasen** [comment]
Can you paste the full log here? Does the user you configured have permissions to create folders where you're trying to deploy (ie. if you try it yourself by sshing into the server does it work)?

**Comment by vipin733** [comment]
when I go to my server and try to make directory manually it not allow with user ubuntu when i change ubuntu to sudo su I can make directory one thing problem is that when i try to give username root it not connect and when i give ubuntu i connect 
so what i have do? I using ec2 ubuntu server

**Comment by Anahkiasen** [comment]
Rocketeer can't do any more than what you yourself are allowed to do on the server, you'll need to grant your ubuntu user the rights to create the folders where you want Rocketeer to, but this is normal behaviour.
