### ISSUE TITLE
[Request] self-update command

### ISSUE THREAD

**Issue by barryvdh** [rocketeers/rocketeer#470]
Is it possible to make a `self-update` command, like composer and other CLI tools?

Right now you have to re-download the files and overwrite them, right? (When using the standalone .phar file).

You are using the Box Project, so does this apply? http://moquet.net/blog/distributing-php-cli/#auto-updates

**Comment by Anahkiasen** [comment]
That's done on 3.0, just not ported to 2.0 yet
