### ISSUE TITLE
after-deploy tasks run when deploy failed

### ISSUE THREAD

**Issue by barryvdh** [rocketeers/rocketeer#471]
See #466 

When deploy is aborted (for example, composer failed), Rocketeer tries to run the 'after' tasks for deploy.

    |=====> An error occured: "Composer could not install dependencies"
    |-- Closure (php artisan assetic:build) fired by deploy.after [~4,55s]
    $ cd /home/user/domains/mydomain.com/application/releases/20150310093616
    $ php artisan assetic:build
    The tasks queue was canceled by task "Deploy"

    // hooks.php
    // Tasks to execute after the core Rocketeer Tasks
	'after'  => array(
		'setup'   => array(),
		'deploy'  => array('php artisan assetic:build'),
		'cleanup' => array(),
	),

**Comment by simplesi** [comment]
I am seeing the same problem in 2.1.2. Not sure if the above is before or ahead of that given how recently this was fixed - but it would be great to see it fixed in the latest stable release.

It looks to me like the same change needs to be made in AbstractTask->fire() in that branch.

**Comment by simplesi** [comment]
@Anahkiasen can we get this fixed on 2.2.x? I'm experiencing the same problem on 2.2.0 - 
any time a deploy fails, rocketeer triggers the success tasks, which is extremely confusing!
