### ISSUE TITLE
how to handle "workbench" composer updates?

### ISSUE THREAD

**Issue by Gompje** [rocketeers/rocketeer#477]
I'm putting some of my app logic inside a package so I can use those for other applications. Since the app is still in development the package itself is still in the workbench folder of my main app. Can you give me some pointers how I would define this in Rocketeer that he has to run composer update first for the workbench and then for the main folder? 

thx!

**Comment by Anahkiasen** [comment]
You could do:

```php
Rocketeer::before('dependencies', function (AbstractTask $task) {
   $workbench = $task->releasesManager->getCurrentReleasePath('workbench');
   
   $task->runInFolder($workbench, [
      'composer install',
   ]);
});
```

Or something of that effect

**Comment by Gompje** [comment]
Thx! this did the trick :)
