### ISSUE TITLE
Cleanup isn't removing the correct directories

### ISSUE THREAD

**Issue by alextyrey** [rocketeers/rocketeer#479]
Here's the (log) output of ```rocketeer cleanup```:
```
20150314150930
20150314162833
20150314164318
20150314164831
20150314165130
20150314170551
20150315134226
20150315134436
20150316144759
$ rm -rf /srv/http/xxxxxxxxx/releases/2147483647 /srv/http/xxxxxxxxx/releases/2147483647 /srv/http/xxxxxxxxx/releases/2147483647 /srv/http/xxxxxxxxx/releases/2147483647 /srv/http/xxxxxxxxx/releases/2147483647
rm -rf /srv/http/xxxxxxxxx/releases/2147483647 /srv/http/xxxxxxxxx/releases/2147483647 /srv/http/xxxxxxxxx/releases/2147483647 /srv/http/xxxxxxxxx/releases/2147483647 /srv/http/xxxxxxxxx/releases/2147483647

|=> Removing <info>5 releases</info> from the server
```
You can see it's trying to rm ```2147483647``` which is completely irrelevant.

**Comment by alextyrey** [comment]
@Anahkiasen is there anything I can do to help you "verify" the bug?

**Comment by Anahkiasen** [comment]
Hm no not really, unverified just means I haven't yet written a failing test for it. If you want to try to submit one via a pull request that can help but besides that, I have to dig in myself. Right now I'm not sure where it could come from :/

**Comment by alextyrey** [comment]
I finally had a chance to look through Rocketeer's code and I found the problem.

You use ```intval``` in ```ReleasesManager::getReleases()```. Intval returns a max integer of ```2147483647``` on 32bit systems. I'm stuck on x32 for the moment, so there you go. :)

**Comment by Anahkiasen** [comment]
Oh. Well that's... rather problematic. I mean I knew PHP had issues with bigints just, first time I actually hit it. Will see what I can do.
