### ISSUE TITLE
Laravel 5 compatibility?

### ISSUE THREAD

**Issue by pvdbroek** [rocketeers/rocketeer#481]
I am trying to install (the great!) rocketeer via composer on a laravel 5 installation, but am getting an error saying it needs illuminate/log 4.2 (see full error below).

(How) is it possible to install rocketeer with laravel 5?

Best regards and thanks in advance!

Pim

Full error:
- Conclusion: don't install laravel/framework v5.0.17
- Conclusion: remove laravel/framework v5.0.16
- Conclusion: don't install laravel/framework v5.0.16
- Conclusion: don't install laravel/framework v5.0.15
- Conclusion: don't install laravel/framework v5.0.14
- Conclusion: don't install laravel/framework v5.0.13
- Conclusion: don't install laravel/framework v5.0.12
- Conclusion: don't install laravel/framework v5.0.11
- Conclusion: don't install laravel/framework v5.0.10
- Conclusion: don't install laravel/framework v5.0.9
- Conclusion: don't install laravel/framework v5.0.8
- Conclusion: don't install laravel/framework v5.0.7
- Conclusion: don't install laravel/framework v5.0.6
- Conclusion: don't install laravel/framework v5.0.5
- Conclusion: don't install laravel/framework v5.0.4
- Conclusion: don't install laravel/framework v5.0.3
- Conclusion: don't install laravel/framework v5.0.2
- Conclusion: don't install laravel/framework v5.0.1
- anahkiasen/rocketeer 2.0.0 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
- anahkiasen/rocketeer 2.0.1 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
- anahkiasen/rocketeer 2.0.2 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
- anahkiasen/rocketeer 2.0.3 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
- anahkiasen/rocketeer 2.0.4 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
- anahkiasen/rocketeer 2.0.5 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
- anahkiasen/rocketeer 2.0.6 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
- anahkiasen/rocketeer 2.1.0 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
- anahkiasen/rocketeer 2.1.1 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
- anahkiasen/rocketeer 2.1.2 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
- don't install illuminate/log v4.2.1|don't install laravel/framework v5.0.0
- don't install illuminate/log v4.2.12|don't install laravel/framework v5.0.0
- don't install illuminate/log v4.2.16|don't install laravel/framework v5.0.0
- don't install illuminate/log v4.2.17|don't install laravel/framework v5.0.0
- don't install illuminate/log v4.2.2|don't install laravel/framework v5.0.0
- don't install illuminate/log v4.2.3|don't install laravel/framework v5.0.0
- don't install illuminate/log v4.2.4|don't install laravel/framework v5.0.0
- don't install illuminate/log v4.2.5|don't install laravel/framework v5.0.0
- don't install illuminate/log v4.2.6|don't install laravel/framework v5.0.0
- don't install illuminate/log v4.2.7|don't install laravel/framework v5.0.0
- don't install illuminate/log v4.2.8|don't install laravel/framework v5.0.0
- don't install illuminate/log v4.2.9|don't install laravel/framework v5.0.0
- Installation request for laravel/framework 5.0.* -> satisfiable by laravel/framework[v5.0.0, v5.0.1, v5.0.10, v5.0.11, v5.0.12, v5.0.13, v5.0.14, v5.0.15, v5.0.16, v5.0.17, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9].
- Installation request for anahkiasen/rocketeer 2.* -> satisfiable by anahkiasen/rocketeer[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.1.0, 2.1.1, 2.1.2].

**Comment by JerseyMilker** [comment]
Yeah I'm not able to install via composer either, globally or within Laravel 5 project :(

**Comment by Anahkiasen** [comment]
See some other issues, use the PHAR or global composer version for Laravel 5 for now.

**Comment by Soufraz** [comment]
Ok, I am using the phar version. How can I create tasks without the facade?
The version installed via composer.json/composer helper us to use the facade Rockteer to create tasks.
Thanks..

**Comment by Soufraz** [comment]
I found. hooks.php key custom. Thanks.

**Comment by publicarray** [comment]
Just wanted to add my error log:

```sh 
composer require --dev anahkiasen/rocketeer
Using version ^2.2 for anahkiasen/rocketeer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for anahkiasen/rocketeer ^2.2 -> satisfiable by anahkiasen/rocketeer[2.2.0].
    - Conclusion: remove laravel/framework v5.2.27
    - Conclusion: don't install laravel/framework v5.2.27
    - anahkiasen/rocketeer 2.2.0 requires illuminate/log ~4.2 -> satisfiable by illuminate/log[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/log v4.2.1|don't install laravel/framework v5.2.27
    - don't install illuminate/log v4.2.12|don't install laravel/framework v5.2.27
    - don't install illuminate/log v4.2.16|don't install laravel/framework v5.2.27
    - don't install illuminate/log v4.2.17|don't install laravel/framework v5.2.27
    - don't install illuminate/log v4.2.2|don't install laravel/framework v5.2.27
    - don't install illuminate/log v4.2.3|don't install laravel/framework v5.2.27
    - don't install illuminate/log v4.2.4|don't install laravel/framework v5.2.27
    - don't install illuminate/log v4.2.5|don't install laravel/framework v5.2.27
    - don't install illuminate/log v4.2.6|don't install laravel/framework v5.2.27
    - don't install illuminate/log v4.2.7|don't install laravel/framework v5.2.27
    - don't install illuminate/log v4.2.8|don't install laravel/framework v5.2.27
    - don't install illuminate/log v4.2.9|don't install laravel/framework v5.2.27
    - Installation request for laravel/framework == 5.2.27.0 -> satisfiable by laravel/framework[v5.2.27].


Installation failed, reverting ./composer.json to its original content.
```
