### ISSUE TITLE
Suggestion: Prompt for connection

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#486]
In config.php, you set a default remote connection. My suggestions is, when you leave it empty, Rocketeer could prompt for the connection key. In my case, this would require me to type "staging" or "production", and by doing so, provides an extra sanity check before deployment proceeds.

**Comment by Anahkiasen** [comment]
Good idea

**Comment by Anahkiasen** [comment]
Done in 24f0200692409df51d67926d333c0c39fe5496d4
