### ISSUE TITLE
Strategy local clone with build script before send to servers

### ISSUE THREAD

**Issue by yannschepens** [rocketeers/rocketeer#487]
Hello,

First of all, thank you for your work.

Before I was using capistrano, and there was a functionnality which disappear in the new release : the local git clone with the build script. (our gitlab is not accessible by external servers)

I just want to know if you will create a strategy to : 
* clone locally the repository
* execute a build script on cloned sources 
* send sources to servers after

I tried the sync strategy, but composer install is executed on each servers and some package are stored into ours gitlab.

Greetings,

Yann Schepens

**Comment by Anahkiasen** [comment]
When you say send the sources you mean like an FTP strategy?

**Comment by yannschepens** [comment]
No, the rsync solution is really good to send files to servers.

Currently the Sync strategy push local sources (./) to remote servers and AFTER execute composer install, and other scripts into sources.

My need is to clone locally (in my machine, into a tmp directory), execute some script (for example: composer, execute less, etc.) and only AFTER send sources to server and execute tasks relative to each server.

There are some benefits to do this : 
* execute only one time composer if you have multiple remote server
* not use sources your are working on (may have some personnal stuff)
* be sure to deploy clean sources
* execute some scripts only one time if there are not relative to server

What do you think about that ?

**Comment by Anahkiasen** [comment]
Yes I see what you mean, what you're talking about is definitely planned for 3.0 but there's nothing like that yet in stable I'm afraid.

**Comment by Anahkiasen** [comment]
I think some people already wrote custom strategies like that though, not sure if they're available on Packagist

**Comment by yannschepens** [comment]
I searched into packagist, but I didn't find anything ... I gonna try to do something ;)

**Comment by Anahkiasen** [comment]
(Tu peux passer sur le chat Gitter si y a besoin d'aide pour quoi que ce soit)
