### ISSUE TITLE
HHVM 3.6.1-version does not contain hiphop anymore.

### ISSUE THREAD

**Issue by Zn4rK** [rocketeers/rocketeer#490]
I recently migrated to HHVM for a project. And when I went and did a deploy with Rocketeer 2.1.3 I noticed that the check for HHVM never did go through. 

The reason for this is that the method isHhvm() tries to check if the word hiphop is in the version constant. 
https://github.com/rocketeers/rocketeer/blob/2.1.3/src/Rocketeer/Binaries/Php.php#L57

The best way according to Facebook is to just check if the constant HHVM_VERSION is defined or not.
http://hhvm.com/blog/2393/hhvm-2-3-0-and-travis-ci

I can't check other versions of HHVM right now, but I think it happend here:
https://github.com/facebook/hhvm/commit/573d6fc0d2745e96ee9775f31dc993919086fc7a

Another strange thing is this command does not work on HHVM 3.6.1.
```
/usr/bin/php -r="print defined('HHVM_VERSION') ? HHVM_VERSION : PHP_VERSION;"
```

This one does:
```
/usr/bin/php -r "print defined('HHVM_VERSION') ? HHVM_VERSION : PHP_VERSION;"
```

Notice the lack of the equal sign after the flag? This is more likely a bug with HHVM though.

**Comment by Anahkiasen** [comment]
That's actually what it does now https://github.com/rocketeers/rocketeer/blob/develop/src/Rocketeer/Binaries/Php.php#L53

Just need to backport it and tag a release

**Comment by Zn4rK** [comment]
Well there we go! Perfect :+1:

**Comment by Anahkiasen** [comment]
Should be fixed on master, will tag a release once some PRs are merged

**Comment by Zn4rK** [comment]
Thank you! :+1:
