### ISSUE TITLE
please help setup guide

### ISSUE THREAD

**Issue by dosarkz** [rocketeers/rocketeer#499]
wget http://rocketeer.autopergamene.eu/versions/rocketeer.phar
$ chmod +x rocketeer.phar
$ mv rocketeer.phar /usr/local/bin/rocketeer

rocketeer ignite

require(phar:///usr/local/bin/rocketeer/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php): failed to open stream: phar error: "vendor/phpunit/phpunit/src/Framew
ork/Assert/Functions.php" is not a file in phar "/usr/local/bin/rocketeer" in phar:///usr/local/bin/rocketeer/vendor/composer/autoload_real.php on line 58                             
PHP Fatal error:  require(): Failed opening required 'phar:///usr/local/bin/rocketeer/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php' (include_path='phar:///usr/local/bin/r
ocketeer/vendor/phpseclib/phpseclib/phpseclib:phar:///usr/local/bin/rocketeer/vendor/phpunit/php-text-template:phar:///usr/local/bin/rocketeer/vendor/phpunit/php-timer:.:/usr/share/ph
p:/usr/share/pear') in phar:///usr/local/bin/rocketeer/vendor/composer/autoload_real.php on line 58

**Comment by Anahkiasen** [comment]
Yes the current Phar got corrupted, trying to fix it
