### ISSUE TITLE
Options for deploy update command

### ISSUE THREAD

**Issue by rauanmaemirov** [rocketeers/rocketeer#500]
I'm opening the question again regarding deploy:update. Most of the time deploy:update calls tend to be minor fixes or fixes that don't require full deploy.

But in fact, full deploy seems to be safer. When you run deploy:update it will pull the changes, clean up and optimise class loader, re-link shared folders, and clear the application cache. So basically it does everything that's being done in a full deploy - but on a live application (for about 10-15 seconds requests will throw 500 error because of re-packaging compiled.php and then users will experience increased latency because less/js assets are being compiled from scratch and models cache is empty).

Previously, I asked to allow options like --no-cache-clear, --no-relink and so on, and I had been answered that it will break the process. The solution to this would be setting up all those steps as post-update hooks. This way, you could always customise tasks pipeline. Since I'm putting my custom tasks in post update hook anyway, I see this solution more flexible than current hard-coded behaviour.

**Comment by Anahkiasen** [comment]
This will be enhanced more in depth with the options system of 3.0-dev, basically currently all tasks can have internal options to configure more in depth each step of the process (like Composer options etc). That being said if your application allows it you should put it in maintenance mode during updates as to not get any incoming request that might disturb the process.
