### ISSUE TITLE
rocketeer.phar binary not up to date with tag 2.2.0

### ISSUE THREAD

**Issue by Zn4rK** [rocketeers/rocketeer#501]
I just downloaded the binary located at http://rocketeer.autopergamene.eu/versions/rocketeer.phar, but it seems like it was not updated to the lastest version.

```
$ php rocketeer.phar --version   
Rocketeer version 2.1.2
```

**Comment by Anahkiasen** [comment]
No it is up to date, just forgot to update the version constant. Need to update the tagging process to be 3.0's where it automatically gets the tag from Git.

**Comment by Konafets** [comment]
Sorry, but it is not up to date. I just downloaded the PHAR yesterday and also got version 2.1.2.
