### ISSUE TITLE
Simplified way to skip installing dependencies

### ISSUE THREAD

**Issue by Cryszon** [rocketeers/rocketeer#502]
Related issue: #200

I use a separate build system to manage and install dependencies locally before uploading the whole build to the server (I've also created a custom deploy strategy for this), which means I need to skip installing dependencies step.

My current workaround for this (as described in #200) is setting `'dependencies' => 'Composer'` and `'composer' => null` in `strategies.php`, which skips installing all the dependencies on deployment. It works, but I think it would be more logical to be able to set `'dependencies' => null` directly. There should at least be a mention in the documentation about the possibility of skipping dependency installation using the workaround I described.

Since I don't have Composer installed on the remote, both `Polyglot` and `Composer` strategies fail with `An error occured: "Composer could not install dependencies"` unless I set `'composer' => null` as explained earlier.

**Comment by Anahkiasen** [comment]
You can set dependencies to null actually, unless I'm mistaken and that wasn't backported to 2, if not I'll backport it and tag a new 2.x release
