### ISSUE TITLE
Incomplete documentation for custom class binaries

### ISSUE THREAD

**Issue by kevinbreed** [rocketeers/rocketeer#505]
The documentation  (http://rocketeer.autopergamene.eu/#/docs/docs/II-Concepts/Binaries) does not describe where to put the file of a custom binary (by extending the AbstractBinary class). I figured out that files placed in the .rocketeer folder are automatically included, so a binaries.php file works and make sense. It would have saved me quite some searching if the documentation had point this out.

**Comment by Anahkiasen** [comment]
Good point. PRs are always welcome to the docs repository, the file you'd want to edit is the following : https://github.com/rocketeers/docs/blob/master/II-Concepts/Binaries.md
