### ISSUE TITLE
shell option does not work for node installed via nvm

### ISSUE THREAD

**Issue by dhampik** [rocketeers/rocketeer#507]
I have installed node js via nvm on Debian server.
I try to use rocketeer for deployment, but when I try to run a task in after deploy hook, it does not recognize npm, though in normal login session everything works well.

With rocketeer I get the following output:
~~~
$ cd admin/frontend
$ bash --login -c 'npm install'
(production) bash: npm: command not found
~~~

I should note, that running `bash --login -c 'npm install'` gives pretty much the same ouput, but if I log in via ssh under that user and run `npm install` or if I run `bash --login` and then run the command it works perfectly fine.

So, I suppose that running `bash --login -c` does not load .bashrc or .profile for the commands which are specified for `-c` option and it should be something else rather than `bash --login -c` for shelled mode.

**Comment by Anahkiasen** [comment]
Hm I don't think that's related, I use NVM successfully with shell mode, are you sure you don't have anything else interfering?

**Comment by dhampik** [comment]
I don't think so, that was a clean Debian 7 setup made just a day ago, nothing special is installed there, just nvm, php, mysql.

**Comment by dhampik** [comment]
And, by the way, if I run `bash --login -c 'nvm list'`on my local Ubuntu desktop, I also get command not found error, but if I run simple `nvm list` everything is fine. So, I suppose there is an issue with commands running via `bash --login -c`

**Comment by dhampik** [comment]
Did a test with both NVM and RVM on a different server, here is the result:
~~~
user@123:~$ rvm list

rvm rubies

   ruby-2.0.0-p594 [ x86_64 ]
   ruby-2.1.3 [ x86_64 ]
=* ruby-2.1.5 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
~~~
~~~
user@123:~$ nvm list
->  v0.10.33
      system
default -> stable (-> v0.10.33)
stable -> 0.10 (-> v0.10.33) (default)
~~~
~~~
user@123:~$ bash --login -c 'nvm list'
bash: nvm: command not found
~~~
~~~
user@123:~$ bash --login -c 'rvm list'

rvm rubies

   ruby-2.0.0-p594 [ x86_64 ]
   ruby-2.1.3 [ x86_64 ]
=* ruby-2.1.5 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
~~~

NVM was installed with the following commands:
~~~
curl https://raw.githubusercontent.com/creationix/nvm/v0.18.0/install.sh | bash

source ~/.nvm/nvm.sh

nvm install stable

nvm use stable

nvm alias default stable
~~~

Looks like there is something with .bashrc of nvm, but don't know what (

**Comment by dhampik** [comment]
For anyone interested, I was able to resolve my issue by adding the following to the end of `.profile` instead of `.bashrc`:

~~~
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
~~~

Still, not sure if that's an issue of nvm or rocketeer, so leaving this issue opened.

**Comment by Anahkiasen** [comment]
Issue is not with Rocketeer indeed, worked everywhere I've used it, this is more of a configuration issue indeed. NVM and RVM are always tricky to work like that since they're booted at login instead of being a functioning globally available binary

**Comment by dhampik** [comment]
OK, I agree, totally true.
@Anahkiasen thanks for quick replies.
