### ISSUE TITLE
Add self-update command

### ISSUE THREAD

**Issue by peregrinphp** [rocketeers/rocketeer#510]
Could you add self-update command to renew the script itself as it is in Composer?

Thank you.

**Comment by Anahkiasen** [comment]
Already done on 3.0-dev, not backported yet

**Comment by Anahkiasen** [comment]
Due to dependencies conflicts (Rocketeer 2 uses a lot of old dependencies that are locked due to Laravel 4 compatibility) this won't be backport-able to the 2.x branch
