### ISSUE TITLE
php vendor/bin/rocketeer does not work for projects located in Windows shared folder

### ISSUE THREAD

**Issue by dhampik** [rocketeers/rocketeer#512]
We have the following workflow:
* we clone project under windows

* we run `vagrant up` which creates and provisions Ubuntu VM

* project directory is a shared folder beetwen Windows and VM

* `composer install` is also executed in project directory in VM

* composer can't create symlink in `vendor/bin` directory, cause it's actually a Windows directory and does not allow Linux symlinks

* composer creates a shell script instead like this one:

<pre>
    #!/usr/bin/env sh
    SRC_DIR="`pwd`"
    cd "`dirname "$0"`"
    cd '../anahkiasen/rocketeer/bin'
    BIN_TARGET="`pwd`/rocketeer"
    cd "$SRC_DIR"
    "$BIN_TARGET" "$@"
</pre>
* this shell script is not working no matter how we run it `php vendor/bin/rocketeer` (just outputs shell script contents) or `bash vendor/bin/rocketeer` (raises Permission denied error on the last line, don't know why exactly)

Hopefully it can be resolved in rocketeer or the instructions of how to run rocketeer under Vagrant from Windows host should be added to the rocketeer installation guide.

**Comment by dhampik** [comment]
For anyone experiencing the same, this is how you can run deploy:
`php vendor/anahkiasen/rocketeer/bin/rocketeer deploy --on="production"`

**Comment by Anahkiasen** [comment]
Good to know, can you PR `rocketeer/docs` with that information? I'll merge it there

**Comment by temalover** [comment]
> For anyone experiencing the same, this is how you can run deploy:
> `php vendor/anahkiasen/rocketeer/bin/rocketeer deploy --on="production"`

Thank you. This issue is working for me!
i moved project on mac os from mamp to local mac server and when i tried to deploy through "php vendor/bin/rocketeer deploy" i had got error:
`Fatal error: Uncaught Error: Class 'Rocketeer\Services\Pathfinder' not found in /Users/artem/Sites/gk/vendor/bin/rocketeer:21
Stack trace:
#0 {main}
  thrown in /Users/artem/Sites/gk/vendor/bin/rocketeer on line 21`
