### ISSUE TITLE
Laravel 5? 

### ISSUE THREAD

**Issue by cerw** [rocketeers/rocketeer#515]
HI is this compatible with Laravel 5 ? 

thanks

**Comment by Anahkiasen** [comment]
The PHAR can be used on any type of application (or as a global composer dependency) but Rocketeer cannot be required as a dependency of a L5 app no (because of Symfony components conflicts and stuff)

**Comment by cve** [comment]
Is there any of full example how to configure Rocketeer with sample Laravel 5 application, with stages, shared .env files, npm, gulp etc.?

**Comment by Anahkiasen** [comment]
No, the documentation will be worked on a bit to include generic examples on how to run builds etc. but nothing that is completed yet. Rocketeer is a standalone package and isn't tied to Laravel anymore, as such there isn't any "special cases" for it in the code. PRs to rocketeers/docs are welcome if anybody wants to help a bit :d
