### ISSUE TITLE
Documenting Quirky Behaviour Plugins

### ISSUE THREAD

**Issue by jaitaiwan** [rocketeers/rocketeer#516]
So, I've been stuck for about three days trying to work out how to do some development with my own Rocketeer plugin. Here's some of my findings:
- Plugins are installed to `~/.rocketeer/vendor` and are not local to the project's vendor.
- This means plugins either have to be installed with the `rocketeer plugin:install` command or you have to manually add your namespace to the `~/.rocketeer/vendor/composer/autoload_psr4.php` file and symlink your plugin

This is likely not a fantastic idea because if you haven't installed the plugin on another system, rocketeer will not always fail and the user may not know that the plugin isn't being run.

So as a result, I think there needs a pull request to allow plugins to be part of either the global home config or local to the project itself perhaps as a config setting.

**Comment by Anahkiasen** [comment]
This was the original intention but I kept having issues with possible dependencies conflicts between your global Composer dependencies and Rocketeer's. As such I decided to isolate Rocketeer in its own Composer scope to reduce the risk of conflict. 

That being said, does Rocketeer really fail silently when a plugin is not installed? Shouldn't it fail, not finding the class you listed in the plugins array?

**Comment by jaitaiwan** [comment]
Well you'd expect it to cause a massive error, but no, unfortunately there's no errors whatsoever.

As far as composer dependencies are concerned, what sort of conflicts did you have. If rocketeer was a global phar then the dependencies should be embeded. It would be a simple matter to require the local project's vendor/autoload.php. If I'm correct, the spl_autoloaders in the local project's vendor will try to be loaded first.

If it was bad enough an issue, perhaps a pull request to composer is in order so that it stores a separate copy for each packagist lib.

**Comment by Anahkiasen** [comment]
Rocketeer's dependencies are embedded in the PHAR, but not the plugins installed afterwards through it, hence the conflicts, or did I not get what you meant?
