### ISSUE TITLE
Different root_directory for production?

### ISSUE THREAD

**Issue by cerw** [rocketeers/rocketeer#517]
Hello, 

I have staging and production but each have differnet root_directory how do i setitup up ? 

thanks

**Comment by cerw** [comment]
Anyone? :)

**Comment by Anahkiasen** [comment]
See contextual configuration http://rocketeer.autopergamene.eu/#/docs/docs/II-Concepts/Connections-and-Stages#contextual-configuration

**Comment by cerw** [comment]
Thanks worked!
