### ISSUE TITLE
ssh credentials on ~/.ssh/config

### ISSUE THREAD

**Issue by gersonfs** [rocketeers/rocketeer#519]
I have multiple users working on a same project. Each user have your own key file, that are specified on ~/.ssh/config. 
Its possible dont specify one path key on rocketeer, making the ssh client to use the specified key in .ssh/config? 

Rocketeer promp every time for a key, but it is specified on ~/.ssh/config, like this:
```
Host myhost.com
     Port xxxx
     IdentityFile ~/.ssh/private.key
```
Thanks!

**Comment by Anahkiasen** [comment]
If you set the `key` to `null` wouldn't that work? Or does Rocketeer ask your for an SSH password if you don't provide the key on 2.x?

**Comment by gersonfs** [comment]
Hi Anahkiasen,

Dont work. Rocketeer version 2.1.2 ask me for a password or key file.
```
gerson@gerson-desktop ~/projects/test $ rocketeer deploy
No password or SSH key is set for [production/0], which would you use? (key) [key/password]
```
Below my config:

```
'connections'      => [
        'production' => [
            'host'      => 'myhost.com',
            'username'  => 'myuser',
            'password'  => '',
            'key'       => null,
            'keyphrase' => '',
            'agent'     => '',
            'db_role'   => true,
        ],
    ],
```

**Comment by Anahkiasen** [comment]
Yes that's what I thought. How would you like this to be handled? My thoughts were maybe if you point Rocketeer to `~/.ssh/config` then it'd defer the key finding to it or something

**Comment by gersonfs** [comment]
My suggestion is more simple, if you are using system calls for ssh: 
When key dont is set, or key is empty or key is null, your system call dont include key parameter, calling ssh client without -i param.

When key is set, call:
```
ssh -i /home/user/.ssh/key command
```
When key dont is set:
```
ssh command
```
This applies to username option too.
ssh client will use global or user settings for the key and other parameters, like port and username.

**Comment by ZeeCoder** [comment]
+1 for detecting the SSH key dynamically.
I actually used another deployment tool for a recent project just because of this issue.

**Comment by Eiskis** [comment]
Kinda having the same issue. For my specific case it would be enough to be able to set

```php
...
'host'      => 'something.something.com,
'username'  => 'username',
'password'  => '',
'key'       => '~/.ssh/private.key',
...
```

...but Rocketeer chokes on the shorthand for home dir (`~`), meaning I have to spell out my username. At least this should work, although itself it's not super dynamic yet. Respecting the SSH config would be good too, but I wouldn't necessarily want the deploy script to be reliant on those.

**Comment by ZeeCoder** [comment]
Exactly. I literally can't use the tool if there's more than one developer involved.

Correction: even one developer can't always use it, since if I work from multiple computers (I have a PC, a laptop and a Mac at work, and I work from every one of them), I might have slightly different names, so the hardcoded ssh key path won't work on every computer.

Also: if I get a request from a client to update a site which I developed half a year ago, I would expect the deployment to go smoothly, regardless of whether I changed my username / reinstalled the whole machine etc.

**Comment by ZeeCoder** [comment]
Could the suggestion made by @gersonfs work @Anahkiasen?
(https://github.com/rocketeers/rocketeer/issues/519#issuecomment-103222240)

**Comment by Stayallive** [comment]
Ran into this also, would be nice if this was somehow made possible!

**Comment by Anahkiasen** [comment]
Path to the SSH key will now be expanded on load so you can use `~/` in it but I'm afraid that's the best phpseclib will let me as far as I know

**Comment by ZeeCoder** [comment]
Thanks for the update!

Unfortunately I can't test it, since I've moved away from devops roles since. :/
