### ISSUE TITLE
Dependency issue?

### ISSUE THREAD

**Issue by ionut-tanasa** [rocketeers/rocketeer#520]
What should I do in this case? 

It's working with 2.1.3 tho ...

    composer require --dev anahkiasen/rocketeer
    Using version ^2.2 for anahkiasen/rocketeer
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

     Problem 1
    - Installation request for anahkiasen/rocketeer ^2.2 -> satisfiable by anahkiasen/rocketeer[2.2.0].
    - Conclusion: remove symfony/translation v2.5.11
    - Conclusion: don't install symfony/translation v2.5.11
    - anahkiasen/rocketeer 2.2.0 requires nesbot/carbon ~1.18 -> satisfiable by nesbot/carbon[1.18.0, 1.19.0].
    - nesbot/carbon 1.18.0 requires symfony/translation 2.6.* -> satisfiable by symfony/translation[v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7].
    - nesbot/carbon 1.19.0 requires symfony/translation ~2.6 -> satisfiable by symfony/translation[v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7].
    - Can only install one of: symfony/translation[v2.6.0, v2.5.11].
    - Can only install one of: symfony/translation[v2.6.1, v2.5.11].
    - Can only install one of: symfony/translation[v2.6.2, v2.5.11].
    - Can only install one of: symfony/translation[v2.6.3, v2.5.11].
    - Can only install one of: symfony/translation[v2.6.4, v2.5.11].
    - Can only install one of: symfony/translation[v2.6.5, v2.5.11].
    - Can only install one of: symfony/translation[v2.6.6, v2.5.11].
    - Can only install one of: symfony/translation[v2.6.7, v2.5.11].
    - Installation request for symfony/translation == 2.5.11.0 -> satisfiable by symfony/translation[v2.5.11].

**Comment by Anahkiasen** [comment]
Try using the global version of Rocketeer or using the PHAR. Issue is one of Rocketeer's dependency uses a version of `symfony/translation` that conflicts with the one required in your app (or by one of the other dependencies of your app).
