### ISSUE TITLE
Error using Slack Notifier

### ISSUE THREAD

**Issue by ionut-tanasa** [rocketeers/rocketeer#521]
I'm using the Laravel package. 

[ErrorException]
  The Symfony\Component\OptionsResolver\OptionsResolver::setOptional method is deprecated since
   version 2.6 and will be removed in 3.0. Use the setDefined() method instead.

**Comment by Anahkiasen** [comment]
Hm this is not really an error with Rocketeer, must be with `illuminate/console` but that'll get changed for Rocketeer 3 anyway.
