### ISSUE TITLE
Move abstracts to their respective namespaces

### ISSUE THREAD

**Issue by Anahkiasen** [rocketeers/rocketeer#526]
eg. `Abstracts\AbstractTask` => `Tasks\AbstractTask`

**Comment by gpupo** [comment]
Why  not ``Abstracts\AbstractTask`` =>  ``Tasks\TaskAbstract`` ?

**Comment by Anahkiasen** [comment]
Cause convention nowadays is mostly `Abstract{Type}`, haven't seen `{Type}Abstract` in a long time

**Comment by gpupo** [comment]
You're right.


 ```
Prefix abstract classes with Abstract. Please note some early Symfony classes do not follow this convention and have not been renamed for backward compatibility reasons. However all new abstract classes must follow this naming convention;
Suffix interfaces with Interface;
```

(http://symfony.com/doc/current/contributing/code/standards.html)

**Comment by Anahkiasen** [comment]
Done
