### ISSUE TITLE
Setting dependencies => null causes an error, and prevents deploy from working

### ISSUE THREAD

**Issue by rickywiens** [rocketeers/rocketeer#531]
This is the error I get when I set dependencies => null inside of my strategies.php file. I installed rocketeer globally using composer today, so it should be the "master" revision (2.2.0, even though the --version command says 2.1.2)

	|-- Dependencies (Installs or update the dependencies on server)

	                                                          
	  [ReflectionException]                                   
	  Class rocketeer.strategies.dependencies does not exist  
	                                                          

	Exception trace:
	 () at /Users/ricky/.composer/vendor/illuminate/container/Illuminate/Container/Container.php:504
	 ReflectionClass->__construct() at /Users/ricky/.composer/vendor/illuminate/container/Illuminate/Container/Container.php:504
	 Illuminate\Container\Container->build() at /Users/ricky/.composer/vendor/illuminate/container/Illuminate/Container/Container.php:428
	 Illuminate\Container\Container->make() at /Users/ricky/.composer/vendor/illuminate/container/Illuminate/Container/Container.php:806
	 Illuminate\Container\Container->offsetGet() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Services/Tasks/TasksBuilder.php:126
	 Rocketeer\Services\Tasks\TasksBuilder->buildStrategy() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Bash.php:67
	 Rocketeer\Bash->getStrategy() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Tasks/Dependencies.php:32
	 Rocketeer\Tasks\Dependencies->execute() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php:143
	 Rocketeer\Abstracts\AbstractTask->Rocketeer\Abstracts\{closure}() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Services/Display/QueueTimer.php:39
	 Rocketeer\Services\Display\QueueTimer->time() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php:144
	 Rocketeer\Abstracts\AbstractTask->fire() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Bash.php:87
	 Rocketeer\Bash->Rocketeer\{closure}() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Services/Display/QueueExplainer.php:58
	 Rocketeer\Services\Display\QueueExplainer->displayBelow() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Bash.php:88
	 Rocketeer\Bash->executeTask() at n/a:n/a
	 call_user_func_array() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Traits/StepsRunner.php:52
	 Rocketeer\Abstracts\AbstractTask->runSteps() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Tasks/Deploy.php:76
	 Rocketeer\Tasks\Deploy->execute() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php:143
	 Rocketeer\Abstracts\AbstractTask->Rocketeer\Abstracts\{closure}() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Services/Display/QueueTimer.php:39
	 Rocketeer\Services\Display\QueueTimer->time() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php:144
	 Rocketeer\Abstracts\AbstractTask->fire() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:190
	 Rocketeer\Services\Tasks\TasksQueue->executeJob() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:122
	 Rocketeer\Services\Tasks\TasksQueue->Rocketeer\Services\Tasks\{closure}() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:222
	 Rocketeer\Services\Tasks\TasksQueue->runSynchronously() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Services/Tasks/TasksQueue.php:130
	 Rocketeer\Services\Tasks\TasksQueue->run() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Abstracts/AbstractCommand.php:173
	 Rocketeer\Abstracts\AbstractCommand->Rocketeer\Abstracts\{closure}() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Abstracts/AbstractCommand.php:270
	 Rocketeer\Abstracts\AbstractCommand->time() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Abstracts/AbstractCommand.php:176
	 Rocketeer\Abstracts\AbstractCommand->fireTasksQueue() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/src/Rocketeer/Console/Commands/DeployCommand.php:39
	 Rocketeer\Console\Commands\DeployCommand->fire() at /Users/ricky/.composer/vendor/illuminate/console/Illuminate/Console/Command.php:112
	 Illuminate\Console\Command->execute() at /Users/ricky/.composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
	 Symfony\Component\Console\Command\Command->run() at /Users/ricky/.composer/vendor/illuminate/console/Illuminate/Console/Command.php:100
	 Illuminate\Console\Command->run() at /Users/ricky/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:889
	 Symfony\Component\Console\Application->doRunCommand() at /Users/ricky/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:193
	 Symfony\Component\Console\Application->doRun() at /Users/ricky/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:124
	 Symfony\Component\Console\Application->run() at /Users/ricky/.composer/vendor/illuminate/support/Illuminate/Support/Facades/Facade.php:205
	 Illuminate\Support\Facades\Facade::__callStatic() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/bin/rocketeer:27
	 Rocketeer\Facades\Console::run() at /Users/ricky/.composer/vendor/anahkiasen/rocketeer/bin/rocketeer:27
	`

This is the full contents of my strategies.php file:

	<?php

	/*
	 * This file is part of Rocketeer
	 *
	 * (c) Maxime Fabre <ehtnam6@gmail.com>
	 *
	 * For the full copyright and license information, please view the LICENSE
	 * file that was distributed with this source code.
	 */

	use Rocketeer\Binaries\PackageManagers\Composer;
	use Rocketeer\Tasks\Subtasks\Primer;

	return [

		// Task strategies
		//
		// Here you can configure in a modular way which tasks to use to
		// execute various core parts of your deployment's flow
		//////////////////////////////////////////////////////////////////////

		// Which strategy to use to check the server
		'check' => 'Php',
		// Which strategy to use to create a new release
		'deploy' => 'Sync',
		// Which strategy to use to test your application
		'test' => null,
		// Which strategy to use to migrate your database
		'migrate' => null,
		// Which strategy to use to install your application's dependencies
		'dependencies' => null,
		// Execution hooks
		//////////////////////////////////////////////////////////////////////
		'composer' => [
			'install' => function (Composer $composer, $task) {
				return $composer->install([], ['--no-interaction' => null, '--no-dev' => null, '--prefer-dist' => null]);
			},
			'update' => function (Composer $composer) {
				return $composer->update();
			},
		],
		// Here you can configure the Primer tasks
		// which will run a set of commands on the local
		// machine, determining whether the deploy can proceed
		// or not
		'primer' => function (Primer $task) {
			return [
				// $task->executeTask('Test'),
				// $task->binary('grunt')->execute('lint'),
			];
		},

	];

Please let me know if you see anything obviously wrong. I'd like to use Rocketeer!

**Comment by rickywiens** [comment]
As an addendum, if I follow the advice in #502 (Setting dependencies to composer, then composer to null in strategies.php) I get the following error:

    |-- Dependencies (Installs or update the dependencies on server)
    The tasks queue was canceled by task "Deploy"
    Execution time: 16.123s

And then in the log file

    sent 5808352 bytes  received 14636 bytes  465839.04 bytes/sec
    total size is 12402893  speedup is 2.13
    /home/testdeploy/.bashrc: line 42: home: command not found
    TERM environment variable not set.
    which: no composer in (/usr/local/bin:/bin:/usr/bin)
    /home/testdeploy/.bashrc: line 42: home: command not found
    TERM environment variable not set.
    which: no composer.phar in (/home/testdeploy/rickywuzhere/www/bold_mvc/releases/20150528103425)

Which makes it seem like it's trying to find the composer executable, failing, and then cancelling the deploy. I am running with the verbose flag on: `rocketeer deploy --verbose`

**Comment by davidfuhr** [comment]
Setting 'dependencies' to null does not work for me either. It is also advised to do so in #435 but does not work.
