### ISSUE TITLE
Sharing folder shouldn't remove the folder first

### ISSUE THREAD

**Issue by matejlauko** [rocketeers/rocketeer#532]
When shared folders are being set up, the order of operations is:

```
rm -rf --> ln -s --> mv -Tf
```

But rm is useless here, because mv -f overwrites the folder and the process is not atomic, so when someone requests the page between rm and mv, the folder doesn't exist.

**Comment by Anahkiasen** [comment]
Hm true, I think that's a leftover of the old symlink procedure that didn't use mv -Tf

**Comment by Anahkiasen** [comment]
I checked and it only removes the existing folder if it's not already a symlink, in which case the operation wouldn't work as mv would throw `mv: cannot overwrite directory 'current/' with non-directory`, so I think this is correct. Will reopen if I missed something
