### ISSUE TITLE
Support stage symlinks using common release folders not separate

### ISSUE THREAD

**Issue by EHLOVader** [rocketeers/rocketeer#534]
I would like the ability to have additional symlinks within a single release folder setup alongside the `current` one.

These would make it easy to transition from a `test` stage to `live` through simply swapping the symlinks. I would know for certain that nothing should go wrong with release since the folder is the exact one I tested against in test.

This could also cut down on duplicate assets by using a single `shared` folder instead of a separate one for each stage.

I don't think this should replace the current stage system, but could be an additional option.

**Comment by EHLOVader** [comment]
I am looking into this again as I configure Rocketeer on another project. I was curious if this has had any further consideration. 

I am looking into it, and I see where the changes might be added, but how they should be configured becomes an issue. Should this be known as a "named release" where you add another option to the command line call like `--name` or `--release` which determines the symlink folder name in place of `current`? Or should it be something more like the stages.

**Comment by Anahkiasen** [comment]
I'm actually opting to not include this as this offers slim benefits over stages – benefits nonetheless but just not big enough to warrant a feature that would need such deep rewrite of some parts of the code. Sorry!
