### ISSUE TITLE
Deploy VCS ignored files?

### ISSUE THREAD

**Issue by benjamincrozat** [rocketeers/rocketeer#535]
Hello,

Is there a way to deploy files you put in .gitignore? Like a config file you don't want in your public repo but obviously need to run your site.

**Comment by Anahkiasen** [comment]
You could hook onto `after.deploy` and use [`$task->upload()`](https://github.com/rocketeers/rocketeer/blob/master/src/Rocketeer/Traits/BashModules/Filesystem.php#L209) to send your remaining files up. All paths in `upload` are relative to the app root (source and destination)
