### ISSUE TITLE
Dependecies

### ISSUE THREAD

**Issue by fromYukki** [rocketeers/rocketeer#537]
Hello guys
Do you plan to update you dependencies? 
You use illuminate/console ~4.2. This library forces me to use symfony/console 2.5.*. But current symfony/console version is 2.7 and it is a big difference between them. The last illuminate/console version uses the last symfony version.
So, if you will update your dependencies in new release is can be very nice for many people.
Thank you

**Comment by Anahkiasen** [comment]
This is done on Rocketeer 3 (develop branch), but not on Rocketeer 2 which has to remain compatible with Laravel 4.2 for BC purposes.
