### ISSUE TITLE
Can't find Symfony deploy scripts

### ISSUE THREAD

**Issue by xtrasmal** [rocketeers/rocketeer#541]
Hello everybody,

I am not lazy, but I have a feeling that nobody works around here. Or is it all Laravel development. 
Can I find some kind of library with cut + paste deploy scripts for Symfony somewhere?
I'd rather deploy Laravel alone.. but life doesnt smile you right in the face most of the time. 

So TLDR;  version:

Care to share Symfony deploy scripts?

**Comment by xtrasmal** [comment]
:+1:

**Comment by Anahkiasen** [comment]
Don't think there is a package for Symfony yet, I know people do deploy Symfony apps with Rocketeer but nobody has yet bundled that into something reusable

**Comment by xtrasmal** [comment]
oke thank you.

**Comment by Anahkiasen** [comment]
It's on the roadmap for Rocketeer 3 tho
