### ISSUE TITLE
The Composer package manager could not be found

### ISSUE THREAD

**Issue by xtrasmal** [rocketeers/rocketeer#543]
Hello everybody. 

``` The Composer package manager could not be found ```

....is what I am getting. I'm still going through the quickstart, so I think I have it set up right. 
I'm deploying from a vagrant box to a server on the network. Both do have composer installed globally.

**Comment by Anahkiasen** [comment]
If Rocketeer is having troubles finding composer you can manually tell it where it is in the `paths.php` file, it'll then just use this path blindly without any further checks. You can use contextual configuration to change this path depending on the environment.
