### ISSUE TITLE
Events not firing when running --on non-default connection

### ISSUE THREAD

**Issue by vicdelfant** [rocketeers/rocketeer#544]
We're using Rocketeer version 2.1.2 with multiple connections (staging and production) with "staging" being the default connection. There's a custom event that clears the application cache but this event does not seem to be fired when deploying to the non-default connection using the `--on` option.

I have checked with `--pretend` and `--verbose` and the entire event is skipped: no error, not even the first `$task->command->info()` is executed. The event is fired properly when running `rocketeer deploy` without the `--on` option or with `--on=staging` (in our case).

**Comment by Anahkiasen** [comment]
How do you register your event?

**Comment by vicdelfant** [comment]
In hooks.php:
```
    // Custom Tasks to register with Rocketeer
    'custom' => [
    	'Application\Prepare'
    ],
```

**Comment by Anahkiasen** [comment]
...well then it's actually weird that it *is* fired cause that's to register tasks with Rocketeer's CLI, not to fire them during deploys. For deploys you'd put the task in `deploy.before` or something

**Comment by vicdelfant** [comment]
Great - I found an undocumented feature :) Looking back at what I did and glancing over the docs for a second time I'm actually wondering why I tried doing it this way. I switched to the proper configuration and it's actually working just fine now.

**Comment by Anahkiasen** [comment]
Yeah the documentation needs a good overhaul, don't hesitate to send a PR to rocketeers/docs if you find something that's really misleading

**Comment by vicdelfant** [comment]
No problem, will certainly do. This was more a case of reading too quickly while trying to get something up and running so no worries.
