### ISSUE TITLE
Rename symbolic link 'current' to another name

### ISSUE THREAD

**Issue by nntoan** [rocketeers/rocketeer#549]
Hello there,

I can rename the 'current' symbolic name with Capistrano, with Rocketeer is there any chance?

**Comment by Anahkiasen** [comment]
No that is not currently doable no, it's hardcoded in a few places. That being said I don't think an option would offer much benefit, Rocketeer is a bit more opinionated than Capistrano so that's why it's currently not changeable. What is your use case?

**Comment by nntoan** [comment]
Actually, I can rename `current` symbolic name with Capistrano, it's allow me override current path in Capfile.

My use case is, I do hard config the my server and I must have a `public` folder or symlink in my application folder. Edit the current configuration to current is impossible because it relate to thousand files....
