### ISSUE TITLE
Cleanup not working correctly on a deploy?

### ISSUE THREAD

**Issue by keithslater** [rocketeers/rocketeer#551]
I currently have my remote.php set as 

    'keep_releases'  => 2,

When I run a deploy, for some reason it will always keep 3 releases on the remote server.

When I run cleanup, it does delete the 3rd and it keeps it at 2 releases.

Is this intended?

**Comment by Anahkiasen** [comment]
I think it may be because Rocketeer officially register the release you're deploying _after_ doing the cleanup so technically it's not part of the count yet when released are purged. Will fix this.
