### ISSUE TITLE
How to access paths or services from tasks?

### ISSUE THREAD

**Issue by goosechaser** [rocketeers/rocketeer#552]
Hi,

I want to run a task and symlink a folder to the current release. How do I access ```\Rocketeer\Services
ReleasesManager``` (or should it be something else) from ```hooks.php```:

```
return array(
	'after' => array(
		'update' => array( function($task) {
            $tests = $task->runForCurrentRelease('ln -s /www  <current release path>');
      }),
	),

);
```

Thanks.

**Comment by Anahkiasen** [comment]
`$task->releasesManager`, [see here](http://rocketeer.autopergamene.eu/#/docs/docs/II-Concepts/Tasks) for the available services on `$task`
