### ISSUE TITLE
Restart Nginx, PHP-fpm after deploy

### ISSUE THREAD

**Issue by tranluan91** [rocketeers/rocketeer#553]
How can I execute commands on different servers after deploying? (for example: restart nginx, restart PHP-fpm etc.)
I used ```sudo /etc/init.d/nginx restart```, but it's an error:  sorry, you must have a tty to run sudo :(
Without edit ```/etc/sudoers```, please help me.
Thanks!

**Comment by GrahamCampbell** [comment]
You mean reload surely?

**Comment by GrahamCampbell** [comment]
You don't want to restart. That will drop all current connections.

**Comment by tranluan91** [comment]
I want to restart Nginx and PHP-fpm. Because after deploy Laravel 4 project with Rocketeer, my system has been cached. The newest releases hasn't applied.
I think I need run nginx and fpm below deploy user.
