### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by yazeed** [rocketeers/rocketeer#555]
Is this going to support Laravel 5 anytime soon?

**Comment by cioxideru** [comment]
look "anahkiasen/rocketeer": "dev-develop",
but 5.1 is not currently supported

**Comment by gvsrepins** [comment]
Any news on the L5 support?

**Comment by samuelecarpene** [comment]
i think you can use it in standalone mode https://github.com/rocketeers/rocketeer/blob/master/README.md#installation

**Comment by Anahkiasen** [comment]
I recommend to use the PHAR in the meantime indeed
