### ISSUE TITLE
Rollback with database migrate (teardown)?

### ISSUE THREAD

**Issue by tpinne** [rocketeers/rocketeer#563]
Hi,

looking at the docs & code I see no possibility to do a database migration together with a rollback. We have migration scripts using Phinx which have up and down methods to build and destroy database changes. Sometimes it is essentially necessary to revert database changes if rolling back a deploy because the previous release might not work with newly changed database.

Any hints or suggestions on that?

Thx in advance and best regards
tpinne

**Comment by mbrodala** [comment]
Have you tried hooking into the process via `before` and `rollback` in your `hooks.php`?

**Comment by Anahkiasen** [comment]
@mbrodala is correct, hooking onto the events of the rollback is the correct way to go about it
