### ISSUE TITLE
Installing Rocketeer gives version 2.1.2, not version 2.2.0 (which is on packagist)

### ISSUE THREAD

**Issue by eXistenZNL** [rocketeers/rocketeer#565]
Hi,

When wgetting http://rocketeer.autopergamene.eu/versions/rocketeer.phar as per installation instructions, I end up with version 2.1.2.

I really need version 2.2.0 though, since that's the version in which the LocalCloneStrategy is added (https://github.com/rocketeers/rocketeer/blob/master/src/Rocketeer/Strategies/Deploy/LocalCloneStrategy.php), which is the only strategy suitable for me until SSH Agent forwarding is added (https://github.com/rocketeers/rocketeer/pull/373) so I can clone remotely with the help of agent forwarding.

Would it be possible that http://rocketeer.autopergamene.eu/versions/rocketeer.phar is updated to v2.2.0? Thanks in advance!

**Comment by RickvdStaaij** [comment]
@Anahkiasen please update the phar file, as the composer installation is having all kinds of collisions

**Comment by mbrodala** [comment]
An option is to [build your own `.phar` file](https://github.com/rocketeers/rocketeer/issues/558#issuecomment-156768450).

**Comment by Anahkiasen** [comment]
Fixed
