### ISSUE TITLE
Verify "rsync" presence on remote system for "sync" deploy strategy

### ISSUE THREAD

**Issue by mbrodala** [rocketeers/rocketeer#567]
If I use the `sync` deployment stratey and the remote system is missing the `rsync` command, the upload silently completes without error and following commands relying on synced files will fail.

A check should be added to ensure `rsync` is really present on the remote system.

**Comment by Anahkiasen** [comment]
SyncStrategy will now go through the `which()` routine which prompts the user for the `rsync` binary if none can be found on server

**Comment by mbrodala** [comment]
Wonderful, thanks!
