### ISSUE TITLE
Make rsync options configurable

### ISSUE THREAD

**Issue by mbrodala** [rocketeers/rocketeer#570]
The `sync` deployment strategy uses `rsync` to copy the local state to the remote server. The command options are currently hardcoded, thus if someone uses e.g. a different Composer `vendor-dir` it is transferred. Excluding the `.rocketeer` directory would also be nice.

Please make the arguments configurable, e.g. via a hook similar to the `composer` dependencies strategy.

**Comment by psren** [comment]
+1 I want to deploy to a server which has no composer installed. So i want to install the dependencies locally and sync them with rsync. I know, it's not perfect, but i'm in need of that. magephp has this one, but lacks on parallel deployments instead.

**Comment by mbrodala** [comment]
I recently implemented exactly this which is basically a combination of the `LocalClone` and the `Composer` strategies. It's actually not hard, you just have to make sure you run all necessary commands `onLocal()`.

**Comment by Anahkiasen** [comment]
Done on Rocketeer 3 through [the options system](https://github.com/rocketeers/rocketeer/blob/develop/src/Rocketeer/Strategies/Deploy/SyncStrategy.php#L28)
