### ISSUE TITLE
laravel 5.1 support, branch "develop" is not work

### ISSUE THREAD

**Issue by cioxideru** [rocketeers/rocketeer#572]
Please add  laravel 5.1 support. We try branch "develop" but it work only with laravel 5.1 and is not working with 5.1

**Comment by rorysmyth** [comment]
badly needed

**Comment by Utwo** [comment]
Up :)

**Comment by Anahkiasen** [comment]
See other threads about the issue. Rocketeer 3 is not meant to be included as a peer dependency anymore, the PHAR is the main way to use it now. Reason for this is I couldn't properly keep Rocketeer agnostic while at the same time being constrained by Laravel's dependencies.
