### ISSUE TITLE
suhosin

### ISSUE THREAD

**Issue by toddaa** [rocketeers/rocketeer#573]
For what its worth...I just ran into a issue in which [suhosin](https://suhosin.org/stories/index.html) was installed on my server and blocking the PHAR from running.  I was getting these messages in the log:

```
ALERT - Include filename ('phar:///usr/local/bin/rocketeer/bin/rocketeer') is an URL that is not allowed (attacker 'REMOTE_ADDR not set', file '/usr/local/bin/rocketeer', line 16)
```

Anyway...I couldn't find much regarding this within the project so I thought I'd leave this for anyone who should run into it in the future:  

http://william.shallum.net/random-notes/suhosinpharurlnotallowed

Hope it helps!

**Comment by Anahkiasen** [comment]
thanks!
