### ISSUE TITLE
Cannot hook into "create-release"

### ISSUE THREAD

**Issue by mbrodala** [rocketeers/rocketeer#574]
Using something like this in the `.rocketeer/hooks.php` doesn't fire the closure:

```php
<?php

return [
  'after' => [
    'create-release' => [
      function($task) { $task->share('file.txt'); }
    ],
  ],
];
```

However, the following works fine as the closure is executed right after e.g. cloning the repository:

```php
<?php

return [
  'after' => [
    'CreateRelease' => [
      function($task) { $task->share('file.txt'); }
    ],
  ],
];
```

Shouldn't the `CreateRelease` task executed by `Deploy` be converted to `create-release` by `AbstractTask::getQualifiedEvent` for `AbstractTask::fireEvent`? The log output actually shows this:

> Closure fired by create-release.after

I'm using version 2.2.0 of Rocketeer.

**Comment by Anahkiasen** [comment]
The issue is that when you use a slug (like `create-release`) Rocketeer tries to retrieve it from the container, however CreateRelease is not bound in it because only CLI tasks (deploy, rollback, etc) are. Will add the other ones to the container so they can be retrieve that way as well

**Comment by Anahkiasen** [comment]
There was also something else, R3 uses `symfony/config` to handle configuration which replaces `-` in array keys by `_` (for YAML compatibility, since R3 also supports JSON and YAML formats).
