### ISSUE TITLE
Bug: fatal: Not a git repository

### ISSUE THREAD

**Issue by ceesvanegmond** [rocketeers/rocketeer#575]
Hi all,

I'm having a problem with rocketeer. I can deploy successfully but I do get an error while running the deploy command (screenshot).
![schermafbeelding 2015-08-21 om 11 50 27](https://cloud.githubusercontent.com/assets/883497/9405780/0ef05630-47fb-11e5-820f-3637f6802080.png)

I'ts really weird because the repo is cloned succesfully. I cannot find out where this error message is comming from. I guess it's doing a `git status` or something?
There's nothing in the log.

LOG:

```
$ git clone "git@xxx:xx/xxx.git" "/home/cees/test/releases/20150821094904" --branch="development" --depth="1"
git clone "git@xxx.xx.xx:xx/xx.git" "/home/cees/test/releases/20150821094904" --branch="development" --depth="1"
Cloning into '/home/cees/test/releases/20150821094904'...
```

**Comment by Anahkiasen** [comment]
Is this Rocketeer 2 or 3?

**Comment by ceesvanegmond** [comment]
@Anahkiasen I don't know anymore. Not using rockteer anymore. Sorry!
