### ISSUE TITLE
Issues with installing Rocketeer inside of Symfony App Vendors directory

### ISSUE THREAD

**Issue by tylerm22** [rocketeers/rocketeer#595]
Hi!

I'm trying to install rocketeer into the vendor directory of a symfony application. Howevever when using the composer installation command, I get the following:

composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v2.7.3
    - Conclusion: don't install symfony/symfony v2.7.3
    - Installation request for anahkiasen/rocketeer ^2.2 -> satisfiable by anahkiasen/rocketeer[2.2.0].
    - Conclusion: don't install symfony/symfony v2.7.2
    - Conclusion: don't install symfony/symfony v2.7.1
    - anahkiasen/rocketeer 2.2.0 requires illuminate/filesystem ~4.2 -> satisfiable by illuminate/filesystem[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - illuminate/filesystem v4.2.1 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/filesystem v4.2.12 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/filesystem v4.2.16 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/filesystem v4.2.17 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/filesystem v4.2.2 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/filesystem v4.2.3 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/filesystem v4.2.4 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/filesystem v4.2.5 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/filesystem v4.2.6 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/filesystem v4.2.7 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/filesystem v4.2.8 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - illuminate/filesystem v4.2.9 requires symfony/finder 2.5.* -> satisfiable by symfony/finder[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - don't install symfony/finder v2.5.0|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.1|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.10|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.11|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.12|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.2|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.3|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.4|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.5|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.6|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.7|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.8|don't install symfony/symfony v2.7.0
    - don't install symfony/finder v2.5.9|don't install symfony/symfony v2.7.0
    - Installation request for symfony/symfony 2.7.* -> satisfiable by symfony/symfony[v2.7.0, v2.7.1, v2.7.2, v2.7.3].

**Comment by tylerm22** [comment]
Update: I've even tried locally adding the files, no success :/

I'm not sure why this is happening. If anyone could help, I'd appreciate it.

Thank you!

**Comment by gwagroves** [comment]
Rocketeer isn't compatible with your version of Symfony.
Rocketeer uses v2.5.* Symfony components, you are using Symfony v2.7.*.

**Comment by tylerm22** [comment]
Thanks! I wound up using develop branch and it works! Have a nice day
