### ISSUE TITLE
rocketeer.phar on http://rocketeer.autopergamene.eu/ missing deps

### ISSUE THREAD

**Issue by adam-paterson** [rocketeers/rocketeer#610]
Can somebody update the phar file on http://rocketeer.autopergamene.eu/. I've just downloaded it and extracted it and it's missing the `"nesbot/carbon": "~1.18"` dependancy which causes `LocalCloneStrategy` to fail.

**Comment by mbrodala** [comment]
Actually the dependency is fine but it's excluded from the built `.phar` which will be fixed once #609 is merged.
