### ISSUE TITLE
Support rollback strategies

### ISSUE THREAD

**Issue by mbrodala** [rocketeers/rocketeer#612]
Instead of hardcoding the symlink switch as only action on `rollback` this should be moved to a `Rollback` strategy. This allows for customizing the tasks to perform on rollback.

To natively support "down" migrations on rollback, the `Migrate` task and the `Migrate` strategy would need a few changes, too. E.g. replace `migrate` with `migrateUp` and add `migrateDown`. (See #563)

**Comment by dinamic** [comment]
+1

**Comment by Anahkiasen** [comment]
Good idea, will add a RollbackStrategy to R3
