### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by rjksn** [rocketeers/rocketeer#615]
- Conclusion: remove laravel/framework v5.1.0
    - Conclusion: don't install laravel/framework v5.1.0

**Comment by samuelecarpene** [comment]
What do you mean?

**Comment by rjksn** [comment]
Composer's only solution to install this, was to not install this for Laravel 5.1. What I posted was composers solution.

I ended up just going with Capistrano. I'm not sure what the du jour deployment systems are, but Capistrano's working now and that's all that matters.

**Comment by Anahkiasen** [comment]
Rocketeer is available as a PHAR and global composer installation, those will be the recommended ways to use it with Rocketeer 3. Installing rocketeer as an app dependency will be deprecated.

**Comment by rjksn** [comment]
Good to know, maybe update the page so that others aren't lost when trying to get it to work. 

Best of luck with everything, I'll check it out for the next project. :)

**Comment by samuelecarpene** [comment]
Rocketeer 3??

**Comment by Anahkiasen** [comment]
@samuelecarpene Yes that's what's on the develop branch, got delayed a lot by feature creep unfortunately so now I'm stuck with some features unfinished and I can't ship it out.
