### ISSUE TITLE
Using @ symbol in password is failing the clone to repo

### ISSUE THREAD

**Issue by dericcain** [rocketeers/rocketeer#616]
URL Example: https://username:P@ssword@github.com/username/project-name.git

When using the @ symbol in a GitHub account password, the clone seems to fail. It is prematurely looking for a domain name that does not exist. Here is the error that I get:

Could not resolve host: ssword@github.com

Obviously, that is not my real password or the explicit error that I am receiving, but you get the point.

**Comment by blade93ny** [comment]
use a URL encoded version of the '@' symbol... which is '%40'
Ex: if you password is 'partOfPass@anotherPartOfPass' then it would be 'partOfPass%40anotherPartOfPass'

**Comment by dericcain** [comment]
That solved it. The first time I ran it after I changes the password, it used my old password (cache?), but the next time it used the correct password and worked. Thanks!
