### ISSUE TITLE
Migrations run before .env is linked

### ISSUE THREAD

**Issue by felixkiss** [rocketeers/rocketeer#617]
I am trying to get migrations to run automatically with each deploy but there are 2 problems:

1) It seems that the migrations try to run before `.env` is linked to `shared/.env` which is bad, because then laravel doesn't know about database config.
2) AFAIK there is no way to pass in `--force` to `php artisan migrate` but it would be needed to make the migrations run on this server.

How would you recommend to tackle these problems?

The relevant part of the deploy log:
```
$ cd /var/www/my-app/releases/20151124010801
$ /usr/bin/php artisan migrate
cd /var/www/my-app/releases/20151124010801
/usr/bin/php artisan migrate
**************************************
*     Application In Production!     *
**************************************

Command Cancelled!
$ ln -s /var/www/my-app/shared/.env /var/www/my-app/releases/20151124010801/.env-temp
$ mv -Tf /var/www/my-app/releases/20151124010801/.env-temp /var/www/my-app/releases/20151124010801/.env
```

**Comment by blade93ny** [comment]
in order to run a migration before, go to hooks.php, and find AFTER section...
// Tasks to execute after the core Rocketeer Tasks
    'after'  => [
        'setup'   => [],
        'deploy'  => [
            $runMigrationsAndSeeds // $task->runForCurrentRelease('php artisan migrate:refresh --seed');
        ],
        'update'  => [
        ],
        'cleanup' => [],
    ],

in remote.php find section SHARED
should look like this...
// A list of folders/file to be shared between releases
    // Use this to list folders that need to keep their state, like
    // user uploaded data, file-based databases, etc.
    'shared'         => [
        '.env'
    ],

NOTE, you need to have a .env file present in shared directory to have it linked... you can do that manually or you can create additional TASK in hooks.php

**Comment by mbrodala** [comment]
@felixkiss I recommend manually sharing this directory after `CreateRelease` in your `hooks.php` like this:

```php
<?php

return [
  'after' => [
    'CreateRelease' => [
      function($task) { $task->share('.env'); }
    ],
  ],
];
```

Notice that it must be `CreateRelease` not `create-release` due to a bug (#574).

**Comment by Anahkiasen** [comment]
Fixed now
