### ISSUE TITLE
Update Rocketeer to latest version on Windows 7

### ISSUE THREAD

**Issue by blade93ny** [rocketeers/rocketeer#619]
Hi, i currently have v2.1.2 installed and i cant seem to upgrade to version 2.2 which seems to be the latest one...
Any help would be greatly appreciated...

**Comment by aik099** [comment]
Can you please add more details on a problem you're having? Can you download latest PHAR file and use it?

**Comment by Anahkiasen** [comment]
The version constant was incorrect, should be fixed in latest version
