### ISSUE TITLE
Call to undefined function Illuminate\Support\mb_strtolower() in the phar

### ISSUE THREAD

**Issue by saurini** [rocketeers/rocketeer#622]
I installed rocketeer using the wget method. When I tried running rocketeer it gave me a fatal error:

    PHP Fatal error:  Call to undefined function Illuminate\Support\mb_strtolower() in phar:///usr/local/bin/rocketeer/vendor/illuminate/support/Illuminate/Support/Str.php on line 295

**Comment by mbrodala** [comment]
This one looks weird. To fix this one could ask the Laravel developers to prepend a leading backslash but in general functions lookup always [falls back to the global namespace](http://php.net/manual/en/language.namespaces.fallback.php).

We are rolling a custom `.phar` here and haven't encountered this issue. How exactly did you invoke the `rocketeer.phar`?

**Comment by vluzrmos** [comment]
It looks like you don't have php mbstring module enabled.

http://php.net/manual/en/book.mbstring.php

**Comment by saurini** [comment]
D'oh! Thanks!

**Comment by aik099** [comment]
@saurini , can you please close the issue if it has been resolved?

**Comment by saurini** [comment]
@aik099 Sorry about that. Closing it now.
