### ISSUE TITLE
How to abort deployment?

### ISSUE THREAD

**Issue by JanisE** [rocketeers/rocketeer#625]
I have set up a "before-symlink" hook for "deploy" task. In that hook I have a case where I want to abort/cancel publishing the release.

    'before-symlink' => ['deploy' => [function ($task) { .. return false; ..}]]

When I try to do it by returning `false`, upon deployment I receive an error message:

    The tasks queue was canceled by task "Deploy"

However, the deployment itself seems to get finished, the `current` symlink is still moved to the supposedly cancelled release.

So, I suppose, the additional hooked commands/tasks are cancelled, but not the deployment itself. What would be the correct approach to cancel/stop the whole deployment?

**Comment by mjanda** [comment]
I have already reported this in #589

**Comment by mjanda** [comment]
As a workaround, I just call die()

**Comment by JanisE** [comment]
OK, thank you for the info!
