### ISSUE TITLE
Q: I have a few submodels in my repo that don't get pulled when deploying; possible to include them?

### ISSUE THREAD

**Issue by Gompje** [rocketeers/rocketeer#627]
Hi,

I'm using some (forked) repos that I defined as submodules in my main repository. Bit new to this but I think all is defined ok: when I work on said forks locally (and check in), I see the submodule code updated of main repository. I use SourceTree to do most of the GIT legwork.

When I update my server with Rocketeer, the submodules don't get checked out nor updated; since I'm a bit pressed in time I'm doing the update manually atm but I think that there is probably a better (and faster) way to do this.

I work on the submodules/main repo simultaneously. The forks are located in the folder structure of the mainrepo for faster development. Atm no modules are updated on other locations.

Can someone point me in the right direction? muchos gracias! :)

**Comment by clieee** [comment]
Hi,

Maybe this is to late for your specific issue, however, I solved it by adding the following to the after update hook:
'update' => ['git pull --recurse-submodules && git submodule update --recursive']

Hope  that helps for future development.
