### ISSUE TITLE
Remove Rocketeer config files after deploy

### ISSUE THREAD

**Issue by drmonkeyninja** [rocketeers/rocketeer#632]
Is there a reason why the `.rocketeer` config files are kept in the release after deployment? This seems to me to be bad practice. If someone has stored passwords in any of their `.rocketeer` config files they would then be found on the server which is not ideal. Should the config files not be automatically removed after deployment?

Currently we're removing the directory after `cleanup` like this:-

```
'cleanup' => [
    'rm -rf .rocketeer',
]
```

**Comment by aik099** [comment]
I agree. Could you please send a PR with that does it (not via hook, but by changing the `cleanup` task).

Not sure if `cleanup` task happens before symlink or not, but the `.rocketeer` folder should be deleted before symlinking of new release has happened.

**Comment by Anahkiasen** [comment]
I don't think that's how it should be handled, Capistrano doesn't delete itself from deployed releases, plus it would mark the release has having unstaged changes if you want to do an update later.

I think the correct way is to simplify credentials handling by adding dotenv support to Rocketeer. So your credentials would be stored in a `.env` like it's common practice nowadays and your Rocketeer config files would just contain `'username' => getenv('SSH_USERNAME')` etc, leaving them safe to be tracked by the repo and to be on the server

**Comment by Anahkiasen** [comment]
Done
