### ISSUE TITLE
@ symbols in git usernames cause issues 

### ISSUE THREAD

**Issue by LewisMcMahon** [rocketeers/rocketeer#633]
You get an error like the bellow

```error: Couldn't resolve host 'lewismcmahon.com:redacted@pathtomyrepo.com/repo.git' while accessing https://lewis@lewismcmahon.com:redacted@pathtomyrepo.com/repo.git``` 

The curret fix is to replace @ with %40 but it would be easy to do this automatically

**Comment by aik099** [comment]
Could you please send a PR with a fix. Also, if possible, reference other websites explaining how this problem can be solved. The `%40` seems like html encoding, but we're doing git commands in command line so it does seem a bit unusual.

**Comment by gophry** [comment]
Facing exact same issue:
abc:p@ssword@github.com leads to fatal error connecting @ssword@github.com

**Comment by aik099** [comment]
PR please. The http://stackoverflow.com/questions/19509028/can-i-use-an-at-symbol-inside-urls page suggests, that encoding individual URL parts (e.g. username, password) might be a good idea. Maybe in PHP there is a solution for URL building that does it automatically. Like `http_build_query` for query string, but for main URL part.

**Comment by LewisMcMahon** [comment]
using the urlencode function of the username should fix it

**Comment by aik099** [comment]
And the `urlencode` was used in https://github.com/rocketeers/rocketeer/commit/99fdb127253fcca3552db6f75bca3e90074eb245 commit. The problem is that this commit is on `develop` branch, while releases are made from `master` branch.

This indicates, that some changes were made since last 2.2.0 release, that aren't released yet.

**Comment by aik099** [comment]
The `Rocketeer\Services\Credentials\Keychains\RepositoriesKeychain` trait where fix was applied in that commit no longer exists as well. I also wasn't able to find any `urlencode` method call in current code.

**Comment by aik099** [comment]
Apparently some huge changes were made in `develop` branch and they got never released.

**Comment by superhaggis** [comment]
A slight aside, but given the unstable state of the develop branch do you think it might be a good idea for the maintainer(s) to salvage code into separate feature branches and re-branch from master once more?

**Comment by aik099** [comment]
Absolutely. In fact that should be the 1st thing in the list after fixing PR merge.

**Comment by Anahkiasen** [comment]
Backported the fix to `master`, will tag a 2.x release soon.
