### ISSUE TITLE
Q: Setting Permissions on shared folders

### ISSUE THREAD

**Issue by sigurros** [rocketeers/rocketeer#635]
Hi,

it seems to me, that setting permissions on shared folders must alway fail, because first the permissions are set, then the linking to the shared folder takes place, removing the folder, which permissions have been set. 

No big deal to set the permissions of shared folders by hand, as they are preserved, just wondering about this. 

I am running version 2.1.2

My remote.php looks like this:
```php

    'shared'         => [
        'app/logs',
        'app/cache',
    ],
    'permissions'    => [

        // The folders and files to set as web writable
        'files'    => [
            'app/logs/',
            'app/cache/',
        ],

        // Here you can configure what actions will be executed to set
        // permissions on the folder above. The Closure can return
        // a single command as a string or an array of commands
        'callback' => function ($task, $file) {
            return [
                sprintf('chmod -R 755 %s', $file),
                sprintf('chmod -R g+s %s', $file),
                sprintf('chown -R deploy:apache %s', $file),
            ];
        },
```

The deployment tells the following:

preview/0 |=> Setting permissions for /var/www/site/app/releases/20160205120005/app/logs
$ cd /var/www/site/app/releases/20160205120005
$ chmod -R 755 /var/www/site/app/releases/20160205120005/app/logs
$ chmod -R g+s /var/www/site/app/releases/20160205120005/app/logs
$ chown -R bibb:apache /var/www/site/app/releases/20160205120005/app/logs
preview/0 |=> Setting permissions for /var/www/site/app/releases/20160205120005/app/cache
$ cd /var/www/site/app/releases/20160205120005
$ chmod -R 755 /var/www/site/app/releases/20160205120005/app/cache
$ chmod -R g+s /var/www/site/app/releases/20160205120005/app/cache
$ chown -R bibb:apache /var/www/site/app/releases/20160205120005/app/cache
preview/0 |=> Sharing file /var/www/site/app/releases/20160205120005/app/logs
$ rm -rf /var/www/site/app/releases/20160205120005/app/logs
$ ln -s /var/www/site/app/shared/app/logs /var/www/site/app/releases/20160205120005/app/logs-temp
$ mv -Tf /var/www/site/app/releases/20160205120005/app/logs-temp /var/www/site/app/releases/20160205120005/app/logs
preview/0 |=> Sharing file /var/www/site/app/releases/20160205120005/app/cache
$ rm -rf /var/www/site/app/releases/20160205120005/app/cache
$ ln -s /var/www/site/app/shared/app/cache /var/www/site/app/releases/20160205120005/app/cache-temp
$ mv -Tf /var/www/site/app/releases/20160205120005/app/cache-temp /var/www/site/app/releases/20160205120005/app/cache

**Comment by drmonkeyninja** [comment]
It seems a bit backwards to set the permissions of shared folders every time we deploy. So our approach is to not set permissions of shared folders on deployment, but instead create the folders on setup and apply the permissions then. So our *hooks.php* file includes the following:-

```php
'after' => [
	'setup' => [
		function ($task) {
			$availableStages = $task->connections->getStages();
			$originalStage = $task->connections->getStage();
			$setPermissions = $task->rocketeer->getOption('remote.permissions.callback');
			// Setup the shared folder structure for each stage on setup
			// and set the correct permissions.
			foreach ($availableStages as $stage) {
				$task->connections->setStage($stage);
				$task->createFolder('app/logs');
				$task->createFolder('app/cache');
				$task->run((array)$setPermissions($task, $task->paths->getFolder('app/logs/')));
				$task->run((array)$setPermissions($task, $task->paths->getFolder('app/cache/')));
			}
			// We need to revert back to the original stage if it was set
			// to ensure that deployment runs as expected.
			if ($originalStage) {
				$task->connections->setStage($originalStage);
			}
		},
	]
]
```

This basically runs through all the configured stages, creates the folders and then sets the permissions, before switching back to the original stage. 

We've found that where a shared folder contains a large number of files changing permissions each time we deploy can really slow things down unnecessarily. That's why we do this on setup as it only needs to be done once.

**Comment by sigurros** [comment]
That`s a great tip. thx! I am just wondering, about the behaviour, which seems to be documented otherwise....
