### ISSUE TITLE
Delay binary resolution in "AbstractBinary" class till actual binary usage

### ISSUE THREAD

**Issue by aik099** [rocketeers/rocketeer#640]
Right now binary resolution in the `AbstractBinary` class is happening right in the constructor. This isn't a problem per se, but for example the `Composer` binary has `getKnownPaths` method looks like this:

```php
protected function getKnownPaths()
{
    return [
        'composer',
        $this->releasesManager->getCurrentReleasePath().'/composer.phar',
    ];
}
```

The above method will connect to 1st server on current connection to see if a `composer.phar` is present inside current release folder. This isn't a problem, when doing a deploy for example, because we need to execute `composer install` as part of it and know where composer is. But this is a problem for other commands, that don't interact with servers, e.g. `rocketeer.phar strategies` is trying to connect to server because of that.

To solve this I'm proposing to change `getBinary` method, that upon 1st call it will resolve the binary and do a `setBinary` on what was resolved. Upon sequential calls it just would return `$this->binary` (as now). This way if we're just creating a binary class and not calling any commands on it no connection to servers would be made. Of course the code, that is using `$this->binary` directly inside `AbstractCommand` class must use `$this->getBinary()` instead.

**Comment by Anahkiasen** [comment]
Good catch, thanks!
