### ISSUE TITLE
Use illumunates version ^5.1 (not ^5.2) in rocketeer v3

### ISSUE THREAD

**Issue by Ellrion** [rocketeers/rocketeer#643]
Laravel 5.1 is LTS. If you have no reason to use 5.2+ versions, then it would be better use 5.1+

**Comment by KiberMath** [comment]
i actualy tried laravel 5.2 with rocketter, but i intalled rocketeer in separate dir.

**Comment by Anahkiasen** [comment]
The illuminate components are for the most part not used anymore within Rocketeer (because semver)
