### ISSUE TITLE
How run local command during deployment

### ISSUE THREAD

**Issue by aik099** [rocketeers/rocketeer#645]
During deployment most commands are executed on current connection/server, but in some cases (e.g. need to invoke AWS command via CLI tool) I need to run some local commands as well through machine on which `rocketeer deploy` command is executed.

Any idea how to configure this?

**Comment by mbrodala** [comment]
Anything that uses the `Core` trait has access to the `onLocal()` method which, well, allows executing commands locally. Have a look at the `LocalClone` or `Sync` strategies examples. This includes basically anything within Rocketeer including strategies and tasks.

**Comment by Anahkiasen** [comment]
As @mbrodala said, `onLocal` is the way to go
