### ISSUE TITLE
The which composer.phar command fails

### ISSUE THREAD

**Issue by marvin255** [rocketeers/rocketeer#647]
Hello. First of all must say that rocketeer makes my life much easier. Thank you!

I'm using Linux so i do not have this problem. When my teammates create repo on windows and add composer.phar it does not have 0770 permissions so `which` command fails. They need to run `git update-index --skip-worktree --chmod=+x composer.phar`.

Is there any way to set right chmod on deploy?

I tried to use `before deploy` hook but seems that it fires too late.

And one more comment. We can not install composer globally on our server.

**Comment by marvin255** [comment]
And one more comment. We can not install composer globally on our server.

**Comment by aik099** [comment]
But this only happens once in each project lifetime, right? Won't it be better to have global install of composer instead?

**Comment by marvin255** [comment]
If there is no any options I will try this.

But it would be very nice if I can put this somwhere in rocketeer deploy script.

**Comment by aik099** [comment]
> If there is no any options I will try this.

You can hook installation of global composer on server as part of `setup` task and never think about this before.

> But it would be very nice if I can put this somwhere in rocketeer deploy script.

I guess you need to debug till the point where `which ...` is executed and see what hook points are available before that. Then add `chrome` command to the `composer.phar` file.

**Comment by marvin255** [comment]
I found a right event "dependencies.before". I have created a composer project, so my teammates can create application skeleton from this project and problem on windows solved now.

Anyway, thanks for help!
