### ISSUE TITLE
composer.json is not in the root of the directory

### ISSUE THREAD

**Issue by kororo** [rocketeers/rocketeer#654]
Hi guys,

I have issue on setting up the Rocketeer for my application. My GIT directories structures looks like this:

- root
  - src
    - composer.json
  - test

I made sure the command "check" gives me good result
`rocketeer check`

Running the command "deploy" gives me error:
`rocketeer deploy`

```
|-- Dependencies (Installs or update the dependencies on server) [~1.44s]
|---- Dependencies/Composer (Installs dependencies with Composer)
$ cd /home/app/releases/20160323144026
$ /usr/local/bin/php /home/lib/composer.phar install --no-interaction --no-dev --prefer-dist
[user@server:2222] (production) Composer could not find a composer.json file in /home/app/releases/20160323144026
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
|===> An error occured: "Composer could not install dependencies"
The tasks queue was canceled by task "Deploy"
```

This happens because my composer.json is not in the root of the app/GIT checkout. Any tips on fixing this issue? I am looking for an option to add "relative path" from the root of current release path to my root of application. (In plain words, I want to add "src" after the current release path)

Tried to dohook before dependency, but it seems not doing the job.

```
Rocketeer::before('dependencies', function ($task)
{
  // go to root of the application
  $task->runForCurrentRelease("cd src");
});

```

**Comment by jimbocooper** [comment]
I'm having the same problem, as my repo's root folder contains several directories with configuration user by Docker, databases and the folder where my code and Laravel installation is "src" yet I can't seem to find a solution that provides that "relative path" to composer or shared folders.

My second scenario can be fixed just by prepopulating the shared paths with /src/ but it'd still be nice to have that functionality out of the box.

**Comment by kororo** [comment]
@jimbocooper I fixed it by adding a hook to a specific event.

Add these code to events.php


```
/*
 // edit to events.php
 // The folder of the application if the basepath is not in the root
  "app_basepath" => "src",
*/
Rocketeer::after("createrelease", function ($task)
{
  $app_basepath = $task->rocketeer->getOption("remote.app_basepath");

  if (!empty($app_basepath))
  {
    // move all the files up by one folder and remove the folder
    $task->runForCurrentRelease(["mv $app_basepath/{.,}* .", "rm -f $app_basepath"]);
  }
});
```

Hopefully core devs will put this as main feature. It is quite important.

**Comment by jimbocooper** [comment]
Good approach! Rather than trying to get into the folder, bring the folder to you. If the mountain won't come to Muhammad then Muhammad must go to the mountain hahaha. 

Thanks a lot for that! Appreciated :)

**Comment by Anahkiasen** [comment]
Rocketeer 3 comes with an option to set if your main application logic point (package managers, migrations, etc) resides in a subfolder of your application, this should solve this use case
