### ISSUE TITLE
getCurrentReleasePath issue

### ISSUE THREAD

**Issue by Biktop** [rocketeers/rocketeer#655]
I came across with strange behaviour next method:
`$task->releasesManager->getCurrentReleasePath()`

**OS**: OSX 10.11.4
**php**: 5.5

**application_name**: 'project'
**root_directory**: '/'
**app_directory**: ''

It seems that problem is in my folder organisation:
```
\project
    releases\
    current\
        domains\
             project\
                  text.txt
```
So if I call in my task:
`echo $task->releasesManager->getCurrentReleasePath('domains/project/text.txt')`
`>> /project/releases/20160323165645/domainstext.txt`

For example if I rename domains/project to domains/project1 then all work correct
`echo $task->releasesManager->getCurrentReleasePath('domains/project1/text.txt')`
`>> /project/releases/20160323165645/domains/project1/text.txt`

**Comment by kororo** [comment]
@Biktop Hey, I had similar issue. Try to do this:

Add these code to events.php


```
/*
 // edit to events.php
 // The folder of the application if the basepath is not in the root
  "app_basepath" => "project/current",
*/
Rocketeer::after("createrelease", function ($task)
{
  $app_basepath = $task->rocketeer->getOption("remote.app_basepath");

  if (!empty($app_basepath))
  {
    // move all the files up by one folder and remove the folder
    $task->runForCurrentRelease(["mv $app_basepath/{.,}* .", "rm -f $app_basepath"]);
  }
});
```

It is because your project root is not in the /

**Comment by Biktop** [comment]
Thanks!

In my case I made next workaround:
```
$currentPath = $task->releasesManager->getCurrentReleasePath();
$content = $task->getFile($currentPath.'/domains/project/text.txt');

```

**Comment by Anahkiasen** [comment]
Is `$task->releasesManager->getCurrentReleasePath('domains/project/text.txt')` the exact command you're running? Because Rocketeer replaces some placeholders in the path arguments, like this:

**paths.php**
```php
'foo' => 'bar',
```

```php
$task->getCurrentReleasePath('{foo}.txt') // releases/1000000/bar
```

Are there any braces in your path that Rocketeer might misinterpret for a pattern which would get [eaten here](https://github.com/rocketeers/rocketeer/blob/master/src/Rocketeer/Services/Pathfinder.php#L213) ?
