### ISSUE TITLE
SSH2.php warnings with PHP 5.6.19 (Ubuntu 16.04)

### ISSUE THREAD

**Issue by tottile** [rocketeers/rocketeer#664]
When deploying on a server with PHP 5.6.19, which is the version of Ubuntu server 16.04:

`PHP Warning:  unpack(): Type N: not enough input, need 4, have 1 in ...\vendor\phpseclib\phpseclib\phpseclib\Net\SSH2.php on line 2826`

and 

`PHP Warning:  extract() expects parameter 1 to be array, boolean given in ...\vendor\phpseclib\phpseclib\phpseclib\Net\SSH2.php on line 2826`

as well as

`PHP Notice:  Undefined variable: length in ...\vendor\phpseclib\phpseclib\phpseclib\Net\SSH2.php on line 2827`

It seems the deployment works anyway though

**Comment by alphabraga** [comment]
same with me

**Comment by finikm** [comment]
Same with php7

**Comment by Anahkiasen** [comment]
This is fixed on Rocketeer 3 which uses a more recent version of phpseclib

**Comment by LoveAndHappiness** [comment]
Where do I find Rocketeer 3?
