### ISSUE TITLE
My password don't work when deploying

### ISSUE THREAD

**Issue by devfelipereis** [rocketeers/rocketeer#667]
Hello guys.

I was trying to deploy my laravel app and it is located at bitbucket. My password has two "$" and I can't deploy cause these symbols turns 20708(and I got an Authentication failed) when rocketeer try to clone my repository. I changed my password and I removed these symbols and now it works fine. 

Any reason for this? I like my passwords more secure :D

**Comment by vedebel** [comment]
Sorry for silly question, but did you put your pass in double quotes?

**Comment by devfelipereis** [comment]
No, I did it with single quotes.

**Comment by vedebel** [comment]
Have you tried adding backslash before every $?

**Comment by devfelipereis** [comment]
Not yet. I don't have time to try this now so I can try later. Thank you!

**Comment by Anahkiasen** [comment]
Will reopen if that has not fixed the issue but yeah escaping the characters should work
