### ISSUE TITLE
How can I perform agent-forward using Rocketeer ?

### ISSUE THREAD

**Issue by merianos** [rocketeers/rocketeer#671]
Hello,

I am using the latest version of `Rocketeer` with Phar and I try to figure out how can I deploy my code on production server using agent forwarding. Is there any option for this ?

**Comment by Anahkiasen** [comment]
If you are using Rocketeer 2 (stable) it does not support agent forwarding as the `phpseclib` version it uses underneath didn't as well. Rocketeer 3 will however, but it's not out yet.
