### ISSUE TITLE
Hooks commands should try to resolve to commands given in paths.php

### ISSUE THREAD

**Issue by Antoniossss** [rocketeers/rocketeer#675]
For example:
I want to perform (cakephp) `php bin/cake.php migrations migrate` after deployment but it is required to run it on PHP7 and with custom php.ini so command looks like that 

`/usr/local/.......php7/bin/php -c /long/path/to/domain/dependant/php.ini migrations migrate`.

Now, in paths.php i have that line defined as `php` command so rocekteer for example launches composer like that: `/usr/local/.......php7/bin/php -c /long/path/to/domain/dependant/php.ini another/long/path/to/composer.phar` and that is fine

So if i have configured `php => /usr/local/.......php7/bin/php -c /long/path/to/domain/dependant/php.ini` in path rocketeer should try to resolve commands from hooks to those given in path as well.

Right now example hook like `after =>[deploy=>php bin/cake.php migrations migrate]` will not resolve the `php` command to the one from paths.php thus resulting in error in my case.

Resolve `php` to the one from paths.php (should also work for custom commands)

**Comment by Anahkiasen** [comment]
Rocketeer cannot extract binaries from a string task, you can however do this:

```php
'after' => function ($task) {
  return $task->php()->run('bin/cake.php migrations migrate');
},
```

That should work. Will reopen if that is not the case.

**Comment by Antoniossss** [comment]
@Anahkiasen this will be definetly close, but but still needs a little help.
Invocation of string command is automaticly preceded with `cd` to current release directory command, while the closure is not. How to get current release path so I can change the directory prior the command?

**Comment by Anahkiasen** [comment]
You can use the `runForCurrentRelease` method which is what string tasks use by default:

```php
'after' => function ($task) {
  return $task->php()->runForCurrentRelease('bin/cake.php migrations migrate');
},
```

**Comment by Antoniossss** [comment]
Yes that is something I found out after checking the docs. Thank you. Maybe adding some php docs for IDE autocompletion could be nice enchancement in some (distant) future releases :) :+1:

**Comment by Anahkiasen** [comment]
That's one of the things I'm trying to think about for Rocketeer 3. Rocketeer has very fine-tuned and complete PHPDocs, the issue is since it resides globally or in a PHAR, most IDEs do not include its classes for autocompletion.
