### ISSUE TITLE
Site assets not updating after deploy

### ISSUE THREAD

**Issue by devfelipereis** [rocketeers/rocketeer#676]
My first deploy was good and everything is working fine.. When I tried to deploy again, it sends my new files and run everything but when I access my site, it shows the old assets.. I have been using rocketeer update that work very well but deploy do not update my files... 

I guess that rocketeer is not updating the symbolic link or something like this.

EDIT:

Symbolic link is right.

Any help? Thanks!

**Comment by Anahkiasen** [comment]
You need to clear PHP OPCache's cache. You can use cachetool's [opcache:reset](https://github.com/gordalina/cachetool) command to do that on the server. Basically PHP's cache doesn't read symlinks so for him it's still the same folder, even if the files inside have changed

**Comment by devfelipereis** [comment]
Nice! It works. Thank you!
