### ISSUE TITLE
Plugin with Binary, how to set remote.shelled?

### ISSUE THREAD

**Issue by nalipaz** [rocketeers/rocketeer#679]
I would like to set my binary in the plugin I am working on to always be shelled. Is there a way to do this without requiring it be set in the projects .rocketeer/remote.php? Thanks.

**Comment by nalipaz** [comment]
My plugin for reference https://github.com/nalipaz/rocketeer-drush

**Comment by Anahkiasen** [comment]
You could overwrite `getCommand` and wrap its return value with `bash --login -c` manually, but I'm afraid there is no way to do that currently no, will think about it for Rocketeer 3

**Comment by nalipaz** [comment]
That's too bad, here is hoping it might be an option in the future. Thanks.

**Comment by Anahkiasen** [comment]
There, if you wanna track progress

**Comment by nalipaz** [comment]
Thanks!
