### ISSUE TITLE
Deployment paths according to connection

### ISSUE THREAD

**Issue by HeatedPillow** [rocketeers/rocketeer#692]
Hello,
i have an question - can i deploy to specific folder according to connection?

I have 2 connections ( stage, live ) and stage deployment folder is in /home/stageweb and live path is in /var/www/html/

How can i deploy into these folders respectively? Thanks

**Comment by mathbr** [comment]
Rewrite your `.rocketeer/config.php` as follows:

```php
<?php

return [
  // ...
  'connections' => [
    'stage' => [
      'servers' => [
        [
          'host' => '...',
          // ...
          'config' => [
            'remote' => [
              'root_directory' => '/home/stageweb'
            ],
          ],
        ],
      ],
    ],
    'live' => [
      'servers' => [
        [
          'host' => '...',
          // ...
          'config' => [
            'remote' => [
              'root_directory' => '/var/www/html'
            ],
          ],
        ],
      ],
    ],
  ],
  // ...
];
```

As soon as you use the `servers` section, you can add the `config` subsection as shown here. The subsections therein represent the configuration files with the same name. Thus the `root_directory` you see above would normally be defined in `.rocketeer/remote.php`.

**Comment by Anahkiasen** [comment]
@mathbr's solution is correct. You can also use contextual configuration with files, ie. create per example `config/connections/production/remote.php` and override the option there.

To be fair it never really made sense for the root directory to be a separate option like that, in Rocketeer 3 it's been moved at the root of the connection (with host, username, password, etc).
