### ISSUE TITLE
Support Tilde (~) to refer to users home folder

### ISSUE THREAD

**Issue by Konafets** [rocketeers/rocketeer#695]
To setup connections in config.php when providing a SSH key you must set a path to that key. To avoid hardcoding the full path like `/Users/foo/.ssh/deploy` it might be a good idea to provide a relative path like `~/.ssh/deploy`.

**Comment by Anahkiasen** [comment]
This is done already in R3, will see if I can backport it maybe

**Comment by harrisred** [comment]
+1
