### ISSUE TITLE
Permission of the cache files in ~/.rocketeer

### ISSUE THREAD

**Issue by sigurros** [rocketeers/rocketeer#698]
Hi,
today I have learned, that rocketeer is caching clear text passwords and passphrases in the cache files in ~/.rocketeer

It would be great if the access rights for this files would be mor restrictive, so only the user can read/write them.

**Comment by Anahkiasen** [comment]
This was an oversight in Rocketeer 2 but has been fixed during the credentials refactor in Rocketeer 3. It's unfortunately not possible to backport the new credentials system in 2.x without breaking changes but I'll push to get 3 out as fast as possible
