### ISSUE TITLE
Dealing with server cache

### ISSUE THREAD

**Issue by richtestani** [rocketeers/rocketeer#701]
I run an onlne shop, and I use Rocketeer to deploy my system to the server.
I have it set to keep 5 releases on the server.

Over the weekend I had pushed the site to the server twice in day - with new changes.
Everything for the most part worked, but when we upload from the admin area, I noticed images were not appearing, but showing missing images. The CMS marked everything as OK - but the image was not there.

I thought a config issue happened or a folder permission problem but that was not the case.
I looked into another release folder, and thats where they were being stored instead of the current one.

The current folder is aliased right but somewhere on the server - the file path is cached.

How can I resolve this now and handle it in the future?
Thanks
Rich

**Comment by keithslater** [comment]
Sounds like it's a problem with your software

**Comment by Anahkiasen** [comment]
Seems like an opcache bug indeed, check the [Troubleshooting](http://rocketeer.autopergamene.eu/VI-Help/Troubleshooting.html) section or use [cachetool](https://github.com/gordalina/cachetool) to clear opcache's cache after deploy. This is unfortunately a bug in opcache and is not something I can work around from the package
