### ISSUE TITLE
Internal Server Error when pathed

### ISSUE THREAD

**Issue by Cranavvo** [rocketeers/rocketeer#706]
I have deployed my application in my root folder successfully and I have three files now in my root folder:

- /shared
- /current (shortcut)
- /releases

I was wondering why when I direct my apache configuration to the current folder to output the current release of my web application on my server that I am receiving and Internal Server Error.

Am I pathing Rocketeer wrongly? @Anahkiasen

**Comment by Anahkiasen** [comment]
No that is correct, are you sure the error doesn't come from somewhere within your application?

**Comment by Cranavvo** [comment]
Sorry, my fault. Reminder to all those migrating to Rocketeer, if you have any .htacess rules pointing to another directory.. change!
