### ISSUE TITLE
Add path to path variable

### ISSUE THREAD

**Issue by imolorhe** [rocketeers/rocketeer#708]
Is there a way to add the path to a binary to the $PATH variable of the terminal on the server before the check command actually runs? Trying to set the path to the git binary on a server (Git isn't in the path by default).

**Comment by Anahkiasen** [comment]
Not as far as I know no, every command is separated so doing an `export` wouldn't work. I think it's best to configure this yourself on the server directly maybe

**Comment by imolorhe** [comment]
@Anahkiasen Okay. Is it possible to set the path to the git binary that should be used? Similar to how the path to the php binary can be set in the paths.php file? I tried that, but it didn't seem to work either.

**Comment by Anahkiasen** [comment]
That's weird, it should have worked, all paths are checked against paths.php. Have you tried running `rocketeer flush` after changing the paths file see if it picked it up after that? Might just be that the resolved path is cached, which would bypass checking the paths.php file

**Comment by imolorhe** [comment]
@Anahkiasen  I've tried that as well.

```
    // Path to the Git binary
    'git'      => '/usr/local/cpanel/3rdparty/bin/git',
```

Still I get `bash: git: command not found` when I run the `check` command. I have also tried adding that path to the PATH variable directly on the server via SSH using the same login credentials, and then git works fine.

**Comment by imolorhe** [comment]
@Anahkiasen I also used the verbose command, and the path to the git binary wasn't used.


```
|=> Checking presence of git
$ git --version
```

Whereas, the path to the PHP binary was used.

```
$ /usr/local/bin/php -r "print defined('HHVM_VERSION');"
```
