### ISSUE TITLE
Error When Composer Runs

### ISSUE THREAD

**Issue by chadwithuhc** [rocketeers/rocketeer#71]
I get the following error when Composer runs. Any idea why this would happen?

```
Generating autoload files
PHP Fatal error:  Class 'Rocketeer\RocketeerServiceProvider' not found in /www/SITE/test/releases/20131206203112/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 123
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Rocketeer\\RocketeerServiceProvider' not found","file":"\/www\/SITE\/test\/releases\/20131206203112\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":123}}Script php artisan optimize handling the post-install-cmd event returned with an error
```

I think I'd like to see auto-running composer as an option. If a user wants to run composer they can create a simple task afterwards. In my case, I don't want to run it.

**Comment by radum** [comment]
I think the best way to do it is to keep it in dev but create a `local` env folder for it and use the app.php config in there to set it up. As per the docs.
