### ISSUE TITLE
Issue 337 is still unresolved.

### ISSUE THREAD

**Issue by infoeon** [rocketeers/rocketeer#710]
I've added some notes to issue 337 explaining further, but essentially complex passwords cause the issue to persist.

The repository url should be parsed using parse_url to properly extract any username and/or password and the remaining components merged again. I would submit a pull request but it appears running the raw source is broken as is building a new PHAR from the recent code so I am unable to fully test it.

**Comment by Anahkiasen** [comment]
Are you trying to build the develop branch or master?

**Comment by infoeon** [comment]
Was able to build after resolving another bug in kherge/box, but the double SVN password issue persists.

**Comment by infoeon** [comment]
Not supporting SVN is a major roadblock.

There is an issue with composer not handling HTTP to HTTPS redirects correctly, and several of your upstream dependencies are also buggy. No rush on this issue since we are deciding to move on to something more stable.

Regards.

**Comment by Anahkiasen** [comment]
Sorry to hear it, but I more than understand. I haven't had a lot of open-source time recently so the project is on the backburner for now. If that's not what you already settled on in the meantime [Deployer](https://deployer.org/) just rolled out a new version, hope this helps
