### ISSUE TITLE
Can it deploy via jumpstations?

### ISSUE THREAD

**Issue by Blizzke** [rocketeers/rocketeer#713]
I've been using capistrano for a while but am looking to cut down on external dependencies, so looking into a PHP solution. Unfortunately so far most can't cope with a jumpstation or so called bastion server (as in you cannot SSH directly to the target server because it is in a DMZ, you have to go trough another). SSH can handle this fine via a ProxyCommand (and Capistrano has no issues with it either (`Net::SSH::Proxy::Command`). PHP solutions however, cannot it seems.

**Comment by Anahkiasen** [comment]
I'm afraid I'm not familiar with jumpstations at all, so I guess it depends on whether the SSH library we use underneath supports it https://github.com/phpseclib/phpseclib

**Comment by Blizzke** [comment]
https://github.com/phpseclib/phpseclib/issues/461 
Guess I'll be sticking with Capistrano for now. Thanks for the reply.
