### ISSUE TITLE
symlink not creating automatically and need help on making my latest release root directory.

### ISSUE THREAD

**Issue by abdulmoiz29** [rocketeers/rocketeer#714]
I am new with rocketeer and really appreciate it if someone could help me out. I have been searching for 3 days now and cannot find any solution, I m using laravel 4.2 and want my code to deploy to root directory or want my root directory to be where ever my current release is.

**Comment by electrosy** [comment]
I'm new to Rocketeer as well. Can you provide more information about your directory structure for your app and your web server setting for the entry path?

**Comment by keithslater** [comment]
Rocketeer doesn't really work that way. It has to have the current, releases, & shared folders. See this file - http://rocketeer.autopergamene.eu/I-Introduction/Whats-Rocketeer.html

**Comment by Anahkiasen** [comment]
That's not currently possible I'm afraid. Rocketeer 3 does support it through strategies but it's not stable yet so it's use at your own risk at the moment. If you are however interested you can grab the current development snapshot [over here](http://rocketeer.autopergamene.eu/versions/rocketeer-develop.phar) – it is recommended to re-ignite to get the latest version of the config files
