### ISSUE TITLE
Manual building instructions

### ISSUE THREAD

**Issue by JanisE** [rocketeers/rocketeer#716]
Can you give us building instructions, please?

Using https://github.com/clue/phar-composer I get a three times bigger phar file which outputs the commands all right if run without arguments, but if I try to deploy, it exits at once and nothing has happened.

The particular problem I would like to solve at this point would be this: https://github.com/phpseclib/phpseclib/pull/674/files But I do not know how to build rocketeer.phar file correctly.

Thanks!

**Comment by Anahkiasen** [comment]
Before anything, ensure that the following setting is disabled in your `php.ini` file:

```ini
[Phar]
; http://php.net/phar.readonly
phar.readonly = Off
```

Then:

```bash
# Clone repository
$ git clone git@github.com:rocketeers/rocketeer.git
$ cd rocketeer

# Install dependencies
$ composer install

# Build PHAR
$ composer build
$ php bin/rocketeer.phar --version
Rocketeer (dev version)
```

**Comment by JanisE** [comment]
Did that. Now I got 5.4 MB "rocketeer.phar" but it still refuses to work.

When I run it without parameters, the difference from running your prepared "rocketeer.phar" is:
* version is "(dev version)" instead of "2.2.3"
* two extra commands have appeared ("debug:...")
* the "Current state" section has only the same "logs" value. There are no "tasks" and "events" entries at all, there is a new "application_name" entry (with no value), the "configuration" entry is empty, and the "application" entry has a different value (full path to the current directory instead of the "application_name" value set in ".rocketeer/config.php")

**Comment by Anahkiasen** [comment]
Ah no but this is to build Rocketeer 3, if you're trying to build Rocketeer 2 you need to checkout the `master` branch, does it work then?

**Comment by JanisE** [comment]
Thank you, it worked! And I am glad to hear that Rocketeer 3 is in works.

**Comment by Anahkiasen** [comment]
It's a bit in pause atm due to work but it's still planned. If you have anything to contribute to the building instructions [over there](https://github.com/rocketeers/rocketeer/blob/develop/CONTRIBUTING.md#building-the-phar), all PRs are welcome (quirks you may have encountered on your platform, etc) o/
