### ISSUE TITLE
Doesn't work with Laravel 5.3

### ISSUE THREAD

**Issue by rkgrep** [rocketeers/rocketeer#718]
There is dependency conflict for Symfony packages (Laravel 5.3 requires 3.1, while Rocketeer requires 3.2)...
It was not triggered with tests: `"illuminate/support": "^5.3"` is not correct dependency, because Laravel does not follow semver. It should have been `"illuminate/support": "5.3.*"`

Is symfony 3.2 really required? Can we fall back to 3.1|3.2 ?

**Comment by Anahkiasen** [comment]
Rocketeer 3 will drop support for adding Rocketeer as an app dependency, instead using the PHAR is the recommended way from now on. The former limited way too much my leeway in dependencies because that meant I had to only use dependencies compatibles with Laravel and Symfony etc etc.
