### ISSUE TITLE
How to deploy Configuration Files with Rocketeer

### ISSUE THREAD

**Issue by LoveAndHappiness** [rocketeers/rocketeer#722]
If you deploy f.e. a Laravel project, it has an `.env` file, that is supposed to not be included in your repository. 

Because this configuration file is missing from your server, the app is not working correctly on the server.

I researched a bit and somebody recommended to create a `dotfiles` directory and store the `.env` config file in there. Then you need to copy the file in your `hooks.php` with this code:

	"after" => [
		"deploy" = [
			"cp ~/dotfiles/.env" /path/to/webroot/.env
		]
	]

That way you would have an .env file. I wonder if this is the recommended way for Rocketeer 2.2.4 as Rocketeer 3 has its own system as you commented [here](https://github.com/rocketeers/rocketeer/issues/703#issuecomment-252641679)

Other people have recommended, to switch entirely to another deployment tool here: http://stackoverflow.com/questions/34153879/how-to-deploy-application-configuration-files-using-rocketeer

I wonder if you could shade some light into this issue, either by coming up with a recommended way for Rocketeer 2 or by telling us, when Rocketeer 3 is going to be released, since I would like to use Rocketeer and not switch to Deployer like others recommend.

Kind regards,

George

**Comment by Anahkiasen** [comment]
The recommended way is to create the `.env` file into the `shared/` folder and add it to the list of shared files so it's symlinked into every release. At least that's how I do, seems to work fine as far as I know. That's true for both Rocketeer 2 and 3 – although Rocketeer 3 would technically allow you to upload a local .env file to shared/ during setup, automating the process a bit more, but the idea would stay the same

**Comment by Anahkiasen** [comment]
That being said if you could have an idea way for it to work in Rocketeer 3 what would it be?

**Comment by LoveAndHappiness** [comment]
> The recommended way is to create the .env file into the shared/ folder and add it to the list of shared files so it's symlinked into every release.

Indeed it works fine like that. And the only improvement I see is the one you already thought about for rocketeer 3, the automatic upload of the file. I'll close the issue now.

By the way, thanks for creating rocketeer. Excellent job.
