### ISSUE TITLE
php function mdecrypt_generic() is deprecated

### ISSUE THREAD

**Issue by langeuh** [rocketeers/rocketeer#729]
```
$ rocketeer -version
Rocketeer version 2.2.5

$ php -v
PHP 7.1.2-3+deb.sury.org~xenial+1 (cli) (built: Feb 22 2017 10:08:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2-3+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0-dev, Copyright (c) 2002-2017, by Derick Rethans

$ which rocketeer
/usr/local/bin/rocketeer
```

when deploying following error gets spit out constantly
```
Deprecated: Function mdecrypt_generic() is deprecated in phar:///usr/local/bin/rocketeer/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php on line 940
```

**Comment by IonutBajescu** [comment]
Just disable the mcrypt extension and the warnings should stop.

**Comment by langeuh** [comment]
I'm using Laravel in a project, so disabling it is not an option since mcrypt is a requirement

**Comment by Anahkiasen** [comment]
The only Laravel 5 version that requires mcrypt is 5.0, all the ones after that are good, is that the one you're on? Cause this is in one of our dependencies and I can't update that dependency without releasing a new major with some heavy changes so it's not an easy fix :/

**Comment by langeuh** [comment]
I'm using Laravel 5.3
I had no idea only 5.0 requires it. I assumed it was always needed and didn't put the effort in turning it off again (since i had trouble installing it :) )

I disabled the extention and now I only get vendor warnings like:
```
Methods with the same name as their class will not be constructors in a future version of PHP; Crypt_RSA has a deprecated constructor in phar:///usr/local/bin/rocketeer/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php on line 273

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Net_SFTP has a deprecated constructor in phar:///usr/local/bin/rocketeer/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 122
```

it's only at the start of the deploy, so i can live with that. And this is not your fault :)
